import fs from 'fs';

// Let's create a robust dataset where every product has:
// - cleanTitle (without emojis, e.g. "Прайм аккаунт CS2 NFA")
// - englishTitle (e.g. "CS2 PRIME NFA ACC")
// - cleanCategory
// - itemType ("medal" | "hours" | "rank" | "knife" | "gloves" | "rust" | "cfg" | "steam" | "vds")
// - badgeLabel
// - summaryPurpose
// - specs { access, hours, medals, rank, vac, warranty, delivery, inactivity }
// - price, oldPrice
// - reviews

const categories = [
  {
    id: 'cs2noprime',
    title: 'АККАУНТЫ CS2 БЕЗ ПРАЙМА',
    shortCategory: 'CS2 NON-PRIME',
    subtitle: 'Аккаунты с медалями, часами и рангами для игры и калибровки',
    count: 310,
    minPrice: 7,
    icon: 'target',
  },
  {
    id: 'cs2nfa',
    title: 'АККАУНТЫ CS2 PRIME NFA',
    shortCategory: 'CS2 PRIME NFA',
    subtitle: 'Прайм-аккаунты с отлегой, ножами, перчатками и рейтингом Премьер',
    count: 247,
    minPrice: 32,
    icon: 'knife',
  },
  {
    id: 'cs2full',
    title: 'АККАУНТЫ CS2 FULL ACCESS',
    shortCategory: 'CS2 FULL ACCESS',
    subtitle: 'Полный доступ с перепривязкой на вашу личную почту и Steam Guard',
    count: 89,
    minPrice: 450,
    icon: 'shield',
  },
  {
    id: 'rust',
    title: 'АККАУНТЫ RUST',
    shortCategory: 'RUST GAME',
    subtitle: 'Лицензионные аккаунты Rust с полным доступом и NFA с отлегой',
    count: 74,
    minPrice: 49,
    icon: 'gear',
  },
  {
    id: 'cs2cfg',
    title: 'КОНФИГИ & НАСТРОЙКИ CS2',
    shortCategory: 'CS2 CFG',
    subtitle: 'Приватные конфиги Midnight, Plague, Memesense, Neverlose, Skeet',
    count: 142,
    minPrice: 39,
    icon: 'chip',
  },
  {
    id: 'steam',
    title: 'STEAM ТОВАРЫ & УСЛУГИ',
    shortCategory: 'STEAM ASSETS',
    subtitle: 'Награды Steam, гифты игр за 30%, подбор аккаунтов и VDS серверы',
    count: 185,
    minPrice: 19,
    icon: 'gift',
  },
];

const products = [
  // ── CS2 БЕЗ ПРАЙМА ──
  {
    id: '1773149575646',
    categoryId: 'cs2noprime',
    cleanTitle: 'АККАУНТ С МЕДАЛЬЮ В CS2',
    englishTitle: 'CS2 ACCOUNT WITH COIN',
    summaryPurpose: 'Профиль для игры и калибровки. Памятная медаль/монета, 180 часов, доступ без Prime.',
    itemType: 'medal',
    price: 15,
    oldPrice: null,
    inactivityDays: 30,
    specs: {
      access: 'Без прайма',
      hours: '180 ч.',
      medals: '1 медаль',
      rank: 'Без прайма',
      vac: 'Чисто',
      warranty: 'Первый вход',
      delivery: 'Автоматическая',
      inactivity: '30 дней',
      emailChange: 'Нет'
    },
    composition: { rank: 20, hours: 40, medals: 60, inventory: 10, access: 30 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 180,
    medalsVal: 1,
    description: `Аккаунт CS2 с памятной монетой / медалью в инвентаре. Наиграно 180 часов. Гарантия действует на момент первого входа в систему.`,
    reviews: [
      { author: 'Flacko_99', rating: 5, text: 'Монета за операцию на месте, за 15р отличный профиль', date: 'Вчера' }
    ]
  },
  {
    id: '1774832016647',
    categoryId: 'cs2noprime',
    cleanTitle: 'АККАУНТ 2 ПРИВАТНЫЙ РАНГ',
    englishTitle: 'CS2 ACC WITH 2 PRIVATE RANK',
    summaryPurpose: 'Готовый аккаунт для входа в соревновательный режим и калибровки.',
    itemType: 'rank',
    price: 12,
    oldPrice: null,
    inactivityDays: 15,
    specs: {
      access: 'Без прайма',
      hours: '45 ч.',
      medals: '0',
      rank: '2 Ранг',
      vac: 'Чисто',
      warranty: 'Первый вход',
      delivery: 'Автоматическая',
      inactivity: '15 дней',
      emailChange: 'Нет'
    },
    composition: { rank: 50, hours: 25, medals: 0, inventory: 0, access: 30 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 45,
    medalsVal: 0,
    description: `Второй приватный ранг уже прокачан — можно сразу начинать калибровку без гринда уровней.`,
    reviews: [
      { author: 'SoloQ_God', rating: 5, text: 'Ранг прокачан, сразу пошел в матчмейкинг', date: '2 дня назад' }
    ]
  },
  {
    id: '1773149644991',
    categoryId: 'cs2noprime',
    cleanTitle: 'АККАУНТ 300+ ЧАСОВ В CS2',
    englishTitle: 'CS2 ACC WITH 300+ HOURS',
    summaryPurpose: 'Аккаунт с солидным запасом наигранных часов для доверенного фактора.',
    itemType: 'hours',
    price: 7,
    oldPrice: null,
    inactivityDays: 30,
    specs: {
      access: 'Без прайма',
      hours: '320 ч.',
      medals: '0',
      rank: 'Калибровка',
      vac: 'Чисто',
      warranty: 'Первый вход',
      delivery: 'Автоматическая',
      inactivity: '30 дней',
      emailChange: 'Нет'
    },
    composition: { rank: 10, hours: 75, medals: 0, inventory: 0, access: 30 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 320,
    medalsVal: 0,
    description: `Наиграно более 300 часов в Counter-Strike 2. Моментальная выдача ключа сразу после оплаты.`,
    reviews: [
      { author: 'kxxxk', rating: 5, text: '320 часов на счетчике, топ за 7 рублей', date: '3 дня назад' }
    ]
  },

  // ── CS2 NFA ──
  {
    id: '1773838287151',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АККАУНТ CS2 NFA (3Ч ГАРАНТИЯ)',
    englishTitle: 'CS2 PRIME NFA (3H WARRANTY)',
    summaryPurpose: 'Базовый Prime статус. Шанс открытого Премьера 50%, возможны скины и медали.',
    itemType: 'medal',
    price: 32,
    oldPrice: null,
    inactivityDays: 35,
    specs: {
      access: 'Prime NFA',
      hours: '650 ч.',
      medals: '2 медали',
      rank: 'Премьер (50%)',
      vac: 'Чисто',
      warranty: '3 часа',
      delivery: 'Автоматическая',
      inactivity: '35 дней',
      emailChange: 'Нет'
    },
    composition: { rank: 40, hours: 55, medals: 40, inventory: 35, access: 60 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 650,
    medalsVal: 2,
    description: `⚡Аккаунт с АВТОВЫДАЧЕЙ (Вы сразу получаете ключ для активации аккаунта!) ∙ Вы сразу можете Играть в CS! (Шанс что будет открыт премьер - 50%) ✅ ∙ Часто на аккаунтах ЕСТЬ СКИНЫ / МЕДАЛИ и т.д💰 ∙ На аккаунтах МОЖНО играть БЕЗ ограничений✅ но нельзя менять пароль и т.д ∙ Если на аккаунте временный vac live, то Гарантия на акк Продлевается на время его действия! ∙ Аккаунты предоставляются С ГАРАНТИЕЙ 3 часа⏰На них МОЖЕТ быть ОТЛЕГА (Например неделя или месяц) ∙ Покупая этот аккаунт, имейте ввиду что он может быть восстановлен. А МОЖЕТ ПРОЖИТЬ НЕСКОЛЬКО НЕДЕЛЬ или МЕСЯЦЕВ! Все зависит от аккаунта который вам попадется.`,
    reviews: [
      { author: 'K0rtex', rating: 5, text: 'Попался акк с медальками, живет уже неделю, за 32 рубля подарок', date: 'Сегодня' },
      { author: 'TimoshaL1ght', rating: 5, text: 'Сразу вошел через программу, премьер открыт!', date: 'Вчера' }
    ]
  },
  {
    id: '1773838416806',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АККАУНТ CS2 NFA (ПРЕМЬЕР, 3Ч ГАРАНТИЯ)',
    englishTitle: 'CS2 PRIME NFA PREMIER ACTIVE',
    summaryPurpose: 'Гарантированно открытый режим Премьер. Отлега от 30 дней.',
    itemType: 'rank',
    price: 42,
    oldPrice: null,
    inactivityDays: 30,
    specs: {
      access: 'Prime NFA',
      hours: '890 ч.',
      medals: '3 медали',
      rank: 'Премьер открыт',
      vac: 'Чисто',
      warranty: '3 часа',
      delivery: 'Автоматическая',
      inactivity: '30 дней',
      emailChange: 'Нет'
    },
    composition: { rank: 70, hours: 65, medals: 50, inventory: 40, access: 60 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 890,
    medalsVal: 3,
    description: `Аккаунт с гарантированно открытым Premier режимом. Идеально для быстрых игр.`,
    reviews: [
      { author: 'Viper_CS', rating: 5, text: 'Премьер открыт, 12к птс', date: 'Вчера' }
    ]
  },
  {
    id: '1775639992648',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АККАУНТ CS2 NFA (4+ МЕДАЛИ)',
    englishTitle: 'CS2 PRIME NFA 4+ MEDALS',
    summaryPurpose: 'Красивый послужной список: 4 и более памятных медалей за службу и операции.',
    itemType: 'medal',
    price: 59,
    oldPrice: null,
    inactivityDays: 45,
    specs: {
      access: 'Prime NFA',
      hours: '1 400 ч.',
      medals: '5 медалей',
      rank: 'Премьер 14k',
      vac: 'Чисто',
      warranty: '3 часа',
      delivery: 'Автоматическая',
      inactivity: '45 дней',
      emailChange: 'Нет'
    },
    composition: { rank: 65, hours: 80, medals: 90, inventory: 45, access: 60 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 1400,
    medalsVal: 5,
    description: `В профиле 4+ медали. Отличный внешний вид послужного списка.`,
    reviews: [
      { author: 'x_shadow', rating: 5, text: 'Медали 2018-2023 года, акк пушка', date: '3 дня назад' }
    ]
  },
  {
    id: '1775641197078',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АККАУНТ CS2 NFA (НОЖ + ПЕРЧАТКИ)',
    englishTitle: 'CS2 PRIME NFA KNIFE AND GLOVES',
    summaryPurpose: 'Эксклюзивный инвентарь: гарантированное наличие ножа и спортивных перчаток.',
    itemType: 'knife',
    price: 209,
    oldPrice: null,
    inactivityDays: 60,
    specs: {
      access: 'Prime NFA',
      hours: '2 100 ч.',
      medals: '6 медалей',
      rank: 'Премьер 16k',
      vac: 'Чисто',
      warranty: '3 часа',
      delivery: 'Автоматическая',
      inactivity: '60 дней',
      emailChange: 'Нет'
    },
    composition: { rank: 80, hours: 90, medals: 85, inventory: 95, access: 60 },
    hasKnife: true,
    hasGloves: true,
    hoursVal: 2100,
    medalsVal: 6,
    description: `На аккаунте ГАРАНТИРОВАННО ЕСТЬ НОЖ И ПЕРЧАТКИ в CS2! Проверяйте инвентарь в игре.`,
    reviews: [
      { author: 'S1mpleFan', rating: 5, text: 'Выпал керамбит и перчатки спецназа, я в шоке за 200р', date: 'Сегодня' }
    ]
  },
  {
    id: '1775641016745',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АККАУНТ CS2 NFA (НОЖ ИЛИ ПЕРЧАТКИ)',
    englishTitle: 'CS2 PRIME NFA KNIFE OR GLOVES',
    summaryPurpose: 'Инвентарь с редким предметом: в CS2 гарантирован нож либо перчатки.',
    itemType: 'knife',
    price: 129,
    oldPrice: 199,
    inactivityDays: 30,
    specs: {
      access: 'Prime NFA',
      hours: '1 250 ч.',
      medals: '4 медали',
      rank: 'Премьер открыт',
      vac: 'Чисто',
      warranty: '3 часа',
      delivery: 'Автоматическая',
      inactivity: '30 дней',
      emailChange: 'Нет'
    },
    composition: { rank: 60, hours: 75, medals: 60, inventory: 85, access: 60 },
    hasKnife: true,
    hasGloves: false,
    hoursVal: 1250,
    medalsVal: 4,
    description: `В инвентаре нож или перчатки CS2. Автовыдача ключа сразу после оплаты.`,
    reviews: []
  },
  {
    id: '1784198119449',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АККАУНТ CS2 NFA (БОЛЬШАЯ ОТЛЕГА + ПРЕМЬЕР)',
    englishTitle: 'CS2 PRIME NFA LONG INACTIVE',
    summaryPurpose: 'Проверенная отлега от 120 дней. Высокая живучесть и надежность профиля.',
    itemType: 'hours',
    price: 77,
    oldPrice: null,
    inactivityDays: 120,
    specs: {
      access: 'Prime NFA',
      hours: '1 800 ч.',
      medals: '4 медали',
      rank: 'Премьер 15k',
      vac: 'Чисто',
      warranty: '3 часа',
      delivery: 'Автоматическая',
      inactivity: '120+ дней',
      emailChange: 'Нет'
    },
    composition: { rank: 70, hours: 85, medals: 65, inventory: 50, access: 70 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 1800,
    medalsVal: 4,
    description: `Крупная проверенная отлега от 120 дней. Высокая стабильность и живучесть аккаунта.`,
    reviews: []
  },
  {
    id: '1775985646591',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АККАУНТ CS2 NFA (НЕСКОЛЬКО НОЖЕЙ, ЖИР)',
    englishTitle: 'CS2 PRIME NFA HIGH PRICE KNIVES',
    summaryPurpose: 'Топовый премиум инвентарь: несколько ножей высшей ценовой категории.',
    itemType: 'knife',
    price: 390,
    oldPrice: null,
    inactivityDays: 60,
    specs: {
      access: 'Prime NFA',
      hours: '3 400 ч.',
      medals: '8 медалей',
      rank: 'Премьер 22k',
      vac: 'Чисто',
      warranty: '3 часа',
      delivery: 'Автоматическая',
      inactivity: '60 дней',
      emailChange: 'Нет'
    },
    composition: { rank: 95, hours: 95, medals: 90, inventory: 100, access: 60 },
    hasKnife: true,
    hasGloves: true,
    hoursVal: 3400,
    medalsVal: 8,
    description: `Жирный инвентарь с несколькими ножами премиум-категории.`,
    reviews: []
  },
  {
    id: '1779354634334',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АККАУНТ CS2 NFA (25K+ РЕЙТИНГ)',
    englishTitle: 'CS2 PRIME NFA 25K+ PREMIER',
    summaryPurpose: 'Элитный рейтинг Premier 25,000+ очков. Высокий соревновательный уровень.',
    itemType: 'rank',
    price: 109,
    oldPrice: null,
    inactivityDays: 30,
    specs: {
      access: 'Prime NFA',
      hours: '2 400 ч.',
      medals: '5 медалей',
      rank: 'Премьер 25k+',
      vac: 'Чисто',
      warranty: '3 часа',
      delivery: 'Автоматическая',
      inactivity: '30 дней',
      emailChange: 'Нет'
    },
    composition: { rank: 100, hours: 90, medals: 75, inventory: 50, access: 60 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 2400,
    medalsVal: 5,
    description: `Высокий Premier рейтинг 25,000+ очков.`,
    reviews: []
  },

  // ── FULL ACCESS CS2 ──
  {
    id: '1773149236916',
    categoryId: 'cs2full',
    cleanTitle: 'ПРАЙМ АККАУНТ CS2 ПОЛНЫЙ ДОСТУП',
    englishTitle: 'CS2 PRIME FULL ACCESS (100% OWNERSHIP)',
    summaryPurpose: 'Полный пожизненный контроль: перепривязка на вашу почту, Steam Guard и телефон.',
    itemType: 'medal',
    price: 450,
    oldPrice: null,
    inactivityDays: 45,
    specs: {
      access: 'Полный доступ',
      hours: '500 ч.',
      medals: '1 медаль',
      rank: 'Калибровка',
      vac: 'Чисто',
      warranty: 'Бессрочно',
      delivery: 'Ручная выдача',
      inactivity: '100% перепривязка',
      emailChange: 'Да'
    },
    composition: { rank: 40, hours: 50, medals: 30, inventory: 30, access: 100 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 500,
    medalsVal: 1,
    description: `Личный аккаунт с Прайм статусом. Полная перепривязка на вашу почту.`,
    reviews: []
  },
  {
    id: '1773149507447',
    categoryId: 'cs2full',
    cleanTitle: 'ПРАЙМ АККАУНТ CS2 (ОТЛЕГА + ПРЕМЬЕР, FULL ACCESS)',
    englishTitle: 'CS2 PRIME FA INACTIVE AND PREMIER',
    summaryPurpose: 'Полный доступ с отлегой 180+ дней и активным Premier рейтингом.',
    itemType: 'rank',
    price: 670,
    oldPrice: 699,
    inactivityDays: 180,
    specs: {
      access: 'Полный доступ',
      hours: '1 400 ч.',
      medals: '3 медали',
      rank: 'Премьер 15k',
      vac: 'Чисто',
      warranty: 'Бессрочно',
      delivery: 'Ручная выдача',
      inactivity: '180+ дней',
      emailChange: 'Да'
    },
    composition: { rank: 75, hours: 80, medals: 60, inventory: 40, access: 100 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 1400,
    medalsVal: 3,
    description: `Полный доступ с солидной отлегой и активным рейтингом Премьер.`,
    reviews: []
  },
  {
    id: '1777990083739',
    categoryId: 'cs2full',
    cleanTitle: 'АККАУНТ С НОЖОМ (ТРЕЙД-БАН, FACEIT READY)',
    englishTitle: 'CS2 KNIFE ACCOUNT TRADE-BAN FACEIT',
    summaryPurpose: 'Дорогой нож в инвентаре. Без VAC, чистый доступ на турнирные платформы Faceit.',
    itemType: 'knife',
    price: 2900,
    oldPrice: 3900,
    inactivityDays: 90,
    specs: {
      access: 'Полный доступ',
      hours: '2 800 ч.',
      medals: '7 медалей',
      rank: 'Faceit Ready',
      vac: 'Чисто',
      warranty: 'Бессрочно',
      delivery: 'Ручная выдача',
      inactivity: 'Чистый Faceit',
      emailChange: 'Да'
    },
    composition: { rank: 90, hours: 95, medals: 90, inventory: 100, access: 100 },
    hasKnife: true,
    hasGloves: true,
    hoursVal: 2800,
    medalsVal: 7,
    description: `Аккаунт с дорогим ножом и трейд-баном. Без VAC-блокировок, доступен Faceit.`,
    reviews: []
  },

  // ── RUST ──
  {
    id: '1773149703177',
    categoryId: 'rust',
    cleanTitle: 'АККАУНТ RUST (ПОЛНЫЙ ДОСТУП)',
    englishTitle: 'RUST FULL ACCESS ACCOUNT',
    summaryPurpose: 'Лицензионная копия Rust со сменой почты и пароля в клиенте Steam.',
    itemType: 'rust',
    price: 450,
    oldPrice: null,
    inactivityDays: 45,
    specs: {
      access: 'Полный доступ',
      hours: '600 ч.',
      medals: '0',
      rank: 'Лицензия Rust',
      vac: 'Чисто',
      warranty: 'На момент покупки',
      delivery: 'Ручная выдача',
      inactivity: '100% перепривязка',
      emailChange: 'Да'
    },
    composition: { rank: 50, hours: 60, medals: 0, inventory: 40, access: 100 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 600,
    medalsVal: 0,
    description: `✅ АККАУНТЫ БЕЗ БЛОКИРОВОК/БАНОВ В РАСТЕ ✅ АККАУНТЫ СО СМЕНОЙ ДАННЫХ Вы получаете ЛОГИН/ПАРОЛЬ и ПОЧТА/ПАРОЛЬ (Вход через клиент Steam) ✅ На аккаунты действует ГАРАНТИЯ на момент покупки.`,
    reviews: [
      { author: 'fuckshadovs', rating: 5, text: 'купил акк с растом, все отлично', date: '10.03.2026' }
    ]
  },
  {
    id: '1775207394067',
    categoryId: 'rust',
    cleanTitle: 'АККАУНТ RUST NFA',
    englishTitle: 'RUST NFA ACCOUNT WITH INACTIVE',
    summaryPurpose: 'Быстрый NFA доступ к игре Rust с проверенной отлегой.',
    itemType: 'rust',
    price: 49,
    oldPrice: 59,
    inactivityDays: 60,
    specs: {
      access: 'Rust NFA',
      hours: '450 ч.',
      medals: '0',
      rank: 'NFA Rust',
      vac: 'Чисто',
      warranty: '3 часа',
      delivery: 'Автоматическая',
      inactivity: '60 дней',
      emailChange: 'Нет'
    },
    composition: { rank: 40, hours: 50, medals: 0, inventory: 20, access: 50 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 450,
    medalsVal: 0,
    description: `NFA доступ к Rust с отлегой. Автовыдача ключа сразу после оплаты.`,
    reviews: []
  },

  // ── CS2 CFG ──
  {
    id: '1779552161498',
    categoryId: 'cs2cfg',
    cleanTitle: 'PLAGUE CS2 CFG',
    englishTitle: 'PLAGUE CS2 PRIVATE CONFIG',
    summaryPurpose: 'Приватный легит/рейдж конфиг: точный спрей, плавные визуалы и авто-настройки.',
    itemType: 'cfg',
    price: 39,
    oldPrice: 79,
    inactivityDays: 0,
    specs: {
      access: 'Конфиг файл',
      hours: '0',
      medals: '0',
      rank: 'Legit / Rage',
      vac: 'Безопасно',
      warranty: 'Мгновенно',
      delivery: 'Автоматическая',
      inactivity: 'Актуально 2026',
      emailChange: 'Нет'
    },
    composition: { rank: 80, hours: 0, medals: 0, inventory: 80, access: 100 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 0,
    medalsVal: 0,
    description: `Приватный легит конфиг для Plague CS2.`,
    reviews: []
  },
  {
    id: '1779552968150',
    categoryId: 'cs2cfg',
    cleanTitle: 'MIDNIGHT CS2 CFG',
    englishTitle: 'MIDNIGHT CS2 PRO LEGIT CONFIG',
    summaryPurpose: 'Флагманский Pro Legit конфиг Midnight: незаметный аимбот, RCS и визуалы.',
    itemType: 'cfg',
    price: 59,
    oldPrice: 109,
    inactivityDays: 0,
    specs: {
      access: 'Конфиг файл',
      hours: '0',
      medals: '0',
      rank: 'Pro Legit',
      vac: 'Безопасно',
      warranty: 'Мгновенно',
      delivery: 'Автоматическая',
      inactivity: 'Актуально 2026',
      emailChange: 'Нет'
    },
    composition: { rank: 95, hours: 0, medals: 0, inventory: 90, access: 100 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 0,
    medalsVal: 0,
    description: `Топовый конфиг Midnight CS2: плавный аим, идеальный спрей.`,
    reviews: [
      { author: 'v1rus_cs', rating: 5, text: 'Конфиг пушка, легит настроен идеально', date: 'Сегодня' }
    ]
  },
  {
    id: '1777982299416',
    categoryId: 'cs2cfg',
    cleanTitle: 'MEMESENSE CS2 CFG',
    englishTitle: 'MEMESENSE CS2 LEGIT CONFIG',
    summaryPurpose: 'Легит настройки Memesense для комфортной игры без подозрений.',
    itemType: 'cfg',
    price: 79,
    oldPrice: 199,
    inactivityDays: 0,
    specs: {
      access: 'Конфиг файл',
      hours: '0',
      medals: '0',
      rank: 'Legit / Visuals',
      vac: 'Безопасно',
      warranty: 'Мгновенно',
      delivery: 'Автоматическая',
      inactivity: 'Актуально 2026',
      emailChange: 'Нет'
    },
    composition: { rank: 85, hours: 0, medals: 0, inventory: 85, access: 100 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 0,
    medalsVal: 0,
    description: `Настройки Memesense CS2 для незаметной игры.`,
    reviews: []
  },
  {
    id: '1777983717957',
    categoryId: 'cs2cfg',
    cleanTitle: 'NEVERLOSE CS2 CFG',
    englishTitle: 'NEVERLOSE CS2 HVH DOMINANCE',
    summaryPurpose: 'Ультимативный HVH и Legit сет Neverlose для доминации на серверах.',
    itemType: 'cfg',
    price: 249,
    oldPrice: null,
    inactivityDays: 0,
    specs: {
      access: 'Конфиг файл',
      hours: '0',
      medals: '0',
      rank: 'HVH Dominance',
      vac: 'Безопасно',
      warranty: 'Мгновенно',
      delivery: 'Автоматическая',
      inactivity: 'Актуально 2026',
      emailChange: 'Нет'
    },
    composition: { rank: 100, hours: 0, medals: 0, inventory: 95, access: 100 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 0,
    medalsVal: 0,
    description: `Мощнейший конфиг Neverlose CS2 для доминации.`,
    reviews: []
  },
  {
    id: '1777983450684',
    categoryId: 'cs2cfg',
    cleanTitle: 'GAMESENSE (SKEET) CS2 CFG',
    englishTitle: 'GAMESENSE SKEET PRIVATE CONFIG',
    summaryPurpose: 'Элитный приватный конфиг для пользователей Gamesense (Skeet).',
    itemType: 'cfg',
    price: 399,
    oldPrice: null,
    inactivityDays: 0,
    specs: {
      access: 'Конфиг файл',
      hours: '0',
      medals: '0',
      rank: 'Skeet Private',
      vac: 'Безопасно',
      warranty: 'Мгновенно',
      delivery: 'Автоматическая',
      inactivity: 'Актуально 2026',
      emailChange: 'Нет'
    },
    composition: { rank: 100, hours: 0, medals: 0, inventory: 100, access: 100 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 0,
    medalsVal: 0,
    description: `Элитный приватный конфиг для Gamesense (Skeet).`,
    reviews: []
  },

  // ── STEAM ──
  {
    id: '1775666229055',
    categoryId: 'steam',
    cleanTitle: '12 НАГРАД STEAM ПРОФИЛЯ',
    englishTitle: '12 STEAM PROFILE AWARDS',
    summaryPurpose: 'Пакет из 12 наград для повышения очков и уровня витрины Steam.',
    itemType: 'steam',
    price: 19,
    oldPrice: null,
    inactivityDays: 0,
    specs: {
      access: 'Очки Steam',
      hours: '0',
      medals: '0',
      rank: 'Очки профиля',
      vac: 'Безопасно',
      warranty: 'Автовыдача',
      delivery: 'Автоматическая',
      inactivity: '12 наград',
      emailChange: 'Нет'
    },
    composition: { rank: 0, hours: 0, medals: 0, inventory: 60, access: 100 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 0,
    medalsVal: 0,
    description: `12 наград для вашего профиля Steam. Быстрое начисление очков.`,
    reviews: []
  },
  {
    id: '1775666358056',
    categoryId: 'steam',
    cleanTitle: '24 НАГРАДЫ STEAM ПРОФИЛЯ',
    englishTitle: '24 STEAM PROFILE AWARDS',
    summaryPurpose: 'Большой пакет из 24 наград для максимальной прокачки профиля Steam.',
    itemType: 'steam',
    price: 59,
    oldPrice: null,
    inactivityDays: 0,
    specs: {
      access: 'Очки Steam',
      hours: '0',
      medals: '0',
      rank: 'Очки профиля',
      vac: 'Безопасно',
      warranty: 'Автовыдача',
      delivery: 'Автоматическая',
      inactivity: '24 награды',
      emailChange: 'Нет'
    },
    composition: { rank: 0, hours: 0, medals: 0, inventory: 80, access: 100 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 0,
    medalsVal: 0,
    description: `24 награды для прокачки профиля Steam.`,
    reviews: []
  },
  {
    id: '1775931316554',
    categoryId: 'steam',
    cleanTitle: 'ГИФТЫ ИГР STEAM НА ВАШ АККАУНТ ЗА 30%',
    englishTitle: 'STEAM GAME GIFTS AT 30% PRICE',
    summaryPurpose: 'Отправка любой доступной игры в виде подарка Steam всего за 30% от её стоимости.',
    itemType: 'steam',
    price: 140,
    oldPrice: null,
    inactivityDays: 0,
    specs: {
      access: 'Steam Gift',
      hours: '0',
      medals: '0',
      rank: 'Подарок Steam',
      vac: 'Безопасно',
      warranty: 'Гарантия выдачи',
      delivery: 'Автоматическая',
      inactivity: 'Подарки Steam',
      emailChange: 'Нет'
    },
    composition: { rank: 0, hours: 0, medals: 0, inventory: 90, access: 100 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 0,
    medalsVal: 0,
    description: `— КАК ЭТО РАБОТАЕТ: ВЫ ПИШЕТЕ НАМ, КАКУЮ ИГРУ ХОТИТЕ ПРИОБРЕСТИ. ОПЛАЧИВАЕТЕ 30% ОТ ЕЕ СТОИМОСТИ (ЕСЛИ ИГРА СТОИТ 1000руб то платите 300руб) И МЫ ОТПРАВЛЯЕМ ВАМ ГИФТ В ВИДЕ ИГРЫ, КОТОРУЮ ВЫ ВЫБРАЛИ! 🔥НАПИШИТЕ в ТГ @HackerShopSupport с пометкой #ГИФТ.`,
    reviews: [
      { author: 'Чебупицца', rating: 5, text: 'Купил раст подарком, поддержка отправила моментально', date: '11.04.2026' }
    ]
  },
  {
    id: '1777559740328',
    categoryId: 'steam',
    cleanTitle: 'ПОДБОР АККАУНТА STEAM ПО ПАРАМЕТРАМ',
    englishTitle: 'CUSTOM STEAM ACCOUNT SEARCH',
    summaryPurpose: 'Индивидуальный поиск аккаунта по нужным играм, уровню, инвентарю и отлеге.',
    itemType: 'steam',
    price: 99,
    oldPrice: null,
    inactivityDays: 0,
    specs: {
      access: 'Подбор',
      hours: '0',
      medals: '0',
      rank: 'Индивидуально',
      vac: 'Чисто',
      warranty: 'Индивидуально',
      delivery: 'Ручная выдача',
      inactivity: 'Ручной подбор',
      emailChange: 'Да'
    },
    composition: { rank: 0, hours: 0, medals: 0, inventory: 70, access: 100 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 0,
    medalsVal: 0,
    description: `Персональный подбор аккаунта Steam с нужными играми, медалями или инвентарём.`,
    reviews: []
  },
  {
    id: '1783963938562',
    categoryId: 'steam',
    cleanTitle: 'ВИРТУАЛЬНЫЕ ВЫДЕЛЕННЫЕ СЕРВЕРЫ (VDS)',
    englishTitle: 'DEDICATED CLOUD VDS SERVERS',
    summaryPurpose: 'Высокоскоростные VDS/VPS для сайтов, ботов, игровых серверов, VPN и разработки.',
    itemType: 'vds',
    price: 99,
    oldPrice: null,
    inactivityDays: 0,
    specs: {
      access: 'VDS Root',
      hours: '24/7',
      medals: '0',
      rank: 'Cloud Linux/Win',
      vac: 'Защита DDoS',
      warranty: '24/7 Поддержка',
      delivery: 'Автоматическая',
      inactivity: 'VDS Cloud',
      emailChange: 'Да'
    },
    composition: { rank: 0, hours: 100, medals: 0, inventory: 90, access: 100 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 0,
    medalsVal: 0,
    description: `Надёжные виртуальные серверы для любых задач: размещения сайтов, веб-приложений, баз данных, игровых серверов, VPN, разработки. Поддержка: @HackVPNSupport`,
    reviews: []
  }
];

const fileContent = `export const CATEGORIES = ${JSON.stringify(categories, null, 2)};\n\nexport const PRODUCTS = ${JSON.stringify(products, null, 2)};\n`;

fs.writeFileSync('c:\\Users\\iliyk\\Desktop\\hackershop-web\\src\\data\\mockData.js', fileContent);
console.log('Cleaned mockData.js with structured passports for all products!');
