import fs from 'fs';

const categories = [
  {
    id: 'cs2nfa',
    title: '🔥CS2 PRIME NFA Аккаунты🔥',
    subtitle: 'Прайм-аккаунты CS2 NFA с отлегой, скинами, ножами и премьером',
    count: 247,
    capacity: 88,
    icon: 'knife',
    badge: 'ОТ 32 ₽',
    minPrice: 32,
  },
  {
    id: 'cs2full',
    title: 'CS2 PRIME FULL ACCESS',
    subtitle: 'Полный доступ с перепривязкой на вашу личную почту',
    count: 89,
    capacity: 65,
    icon: 'shield',
    badge: 'ОТ 450 ₽',
    minPrice: 450,
  },
  {
    id: 'cs2noprime',
    title: 'CS2 БЕЗ ПРАЙМА',
    subtitle: 'Аккаунты с медалями, наигранными часами и 2 приватным рангом',
    count: 310,
    capacity: 95,
    icon: 'target',
    badge: 'ОТ 7 ₽',
    minPrice: 7,
  },
  {
    id: 'rust',
    title: 'RUST ⚙️',
    subtitle: 'Лицензионные аккаунты Rust с полным доступом и NFA',
    count: 74,
    capacity: 55,
    icon: 'gear',
    badge: 'ОТ 49 ₽',
    minPrice: 49,
  },
  {
    id: 'cs2cfg',
    title: 'CS2 CFG & НАСТРОЙКИ',
    subtitle: 'Приватные конфиги Midnight, Plague, Memesense, Neverlose, Skeet',
    count: 142,
    capacity: 94,
    icon: 'chip',
    badge: 'ОТ 39 ₽',
    minPrice: 39,
  },
  {
    id: 'steam',
    title: 'Steam Товары',
    subtitle: 'Награды Steam, гифты игр за 30%, подбор аккаунтов и VDS серверы',
    count: 185,
    capacity: 80,
    icon: 'gift',
    badge: 'ОТ 19 ₽',
    minPrice: 19,
  },
];

const products = [
  // ── CS2 NFA ──
  {
    id: '1773838287151',
    categoryId: 'cs2nfa',
    categoryName: '🔥CS2 PRIME NFA Аккаунты🔥',
    title: '☘️ПРАЙМ АКК CS2 NFA (3ч гарант) ∙ CS2 PRIME NFA (3h warranty)',
    rarity: 'classified',
    rarityName: 'Топ продаж',
    price: 32,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: '3 часа',
    inactivity: 'Есть отлега',
    hours: 650,
    rank: 'Премьер (шанс 50%)',
    hasKnife: false,
    hasGloves: false,
    medals: 2,
    steamLevel: 8,
    region: 'RU / CIS',
    description: `⚡Аккаунт с АВТОВЫДАЧЕЙ (Вы сразу получаете ключ для активации аккаунта!) ∙ Вы сразу можете Играть в CS! (Шанс что будет открыт премьер - 50%) ✅ ∙ Часто на аккаунтах ЕСТЬ СКИНЫ / МЕДАЛИ и т.д💰 ∙ На аккаунтах МОЖНО играть БЕЗ ограничений✅ но нельзя менять пароль и т.д ∙ Если на аккаунте временный vac live, то Гарантия на акк Продлевается на время его действия! ∙ Аккаунты предоставляются С ГАРАНТИЕЙ 3 часа⏰На них МОЖЕТ быть ОТЛЕГА (Например неделя или месяц) ∙ Покупая этот аккаунт, имейте ввиду что он может быть восстановлен. А МОЖЕТ ПРОЖИТЬ НЕСКОЛЬКО НЕДЕЛЬ или МЕСЯЦЕВ! Все зависит от аккаунта который вам попадется.`,
    reviews: [
      { author: 'K0rtex', rating: 5, text: 'Попался акк с медальками, живет уже неделю, за 30 рублей - считаю подарок < 3', date: 'Сегодня' },
      { author: 'TimoshaL1ght', rating: 5, text: 'Всё четко, сразу вошел через прогу, премьер открыт!', date: 'Вчера' },
      { author: 'Uki_iz_podvala', rating: 5, text: 'Ворк нфашка, есть небольшой инвент', date: '2 дня назад' },
      { author: 'kxxxk', rating: 5, text: 'Топ нфа акки, постоянно беру', date: '3 дня назад' },
    ]
  },
  {
    id: '1773838416806',
    categoryId: 'cs2nfa',
    categoryName: '🔥CS2 PRIME NFA Аккаунты🔥',
    title: '🍋ПРАЙМ АКК CS2 NFA (Премьер, 3ч гарант) ∙ CS2 PRIME NFA (Premier , 3h warranty)',
    rarity: 'classified',
    rarityName: 'Топ продаж',
    price: 42,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: '3 часа',
    inactivity: '30+ дней',
    hours: 890,
    rank: 'Премьер 100%',
    hasKnife: false,
    hasGloves: false,
    medals: 3,
    steamLevel: 12,
    region: 'RU / CIS',
    description: `⚡Аккаунт с гарантированно открытым режимом ПРЕМЬЕР! Автовыдача ключа сразу после оплаты.`,
    reviews: [
      { author: 'Flacko', rating: 5, text: 'Премьер 14к птс, отлега месяц, топ за 42 рубля', date: 'Вчера' }
    ]
  },
  {
    id: '1775639992648',
    categoryId: 'cs2nfa',
    categoryName: '🔥CS2 PRIME NFA Аккаунты🔥',
    title: '💎ПРАЙМ АКК CS2 NFA (4+ Медали, 3ч гарант) ∙ CS2 PRIME NFA ACC (4+ medals, 3h warranty)',
    rarity: 'classified',
    rarityName: 'Топ продаж',
    price: 59,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: '3 часа',
    inactivity: '45 дней',
    hours: 1400,
    rank: 'Премьер открыт',
    hasKnife: false,
    hasGloves: false,
    medals: 5,
    steamLevel: 16,
    region: 'RU / CIS',
    description: `Красивый профиль с 4+ памятными медалями (служба, операции, монеты).`,
    reviews: [
      { author: 'x_shadow', rating: 5, text: 'Медали 2018-2023 года, акк пушка', date: '3 дня назад' }
    ]
  },
  {
    id: '1775641197078',
    categoryId: 'cs2nfa',
    categoryName: '🔥CS2 PRIME NFA Аккаунты🔥',
    title: '👑ПРАЙМ АКК CS2 NFA (Нож + Перчатки) ∙ CS2 PRIME NFA ACC (Knife + Gloves)',
    rarity: 'covert',
    rarityName: 'Эксклюзив',
    price: 209,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: '3 часа',
    inactivity: '60 дней',
    hours: 2100,
    rank: 'Премьер 16k',
    hasKnife: true,
    hasGloves: true,
    medals: 6,
    steamLevel: 25,
    region: 'RU / CIS',
    description: `На аккаунте ГАРАНТИРОВАННО ЕСТЬ НОЖ И ПЕРЧАТКИ в CS2! Проверяйте инвентарь в игре.`,
    reviews: [
      { author: 'S1mpleFan', rating: 5, text: 'Выпал керамбит и перчатки спецназа, я в шоке за 200р', date: 'Сегодня' }
    ]
  },
  {
    id: '1775641016745',
    categoryId: 'cs2nfa',
    categoryName: '🔥CS2 PRIME NFA Аккаунты🔥',
    title: '❄️ПРАЙМ АКК CS2 NFA (Нож / Перчатки) ∙ CS2 PRIME NFA (Knife / Gloves)',
    rarity: 'covert',
    rarityName: 'Скидка',
    price: 129,
    oldPrice: 199,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: '3 часа',
    inactivity: '30 дней',
    hours: 1250,
    rank: 'Премьер открыт',
    hasKnife: true,
    hasGloves: false,
    medals: 4,
    steamLevel: 14,
    region: 'RU / CIS',
    description: `В инвентаре нож или перчатки CS2. Автовыдача ключа сразу после оплаты.`,
    reviews: []
  },
  {
    id: '1784198119449',
    categoryId: 'cs2nfa',
    categoryName: '🔥CS2 PRIME NFA Аккаунты🔥',
    title: '🍕ПРАЙМ АКК CS2 NFA (Большая отлега + ПРЕМЬЕР) ∙ CS2 PRIME NFA (long inactive + PREMIER)',
    rarity: 'classified',
    rarityName: 'Топ продаж',
    price: 77,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: '3 часа',
    inactivity: '120+ дней',
    hours: 1800,
    rank: 'Премьер 15k',
    hasKnife: false,
    hasGloves: false,
    medals: 4,
    steamLevel: 18,
    region: 'RU / CIS',
    description: `Крупная проверенная отлега от 120 дней. Высокая стабильность и живучесть аккаунта.`,
    reviews: []
  },
  {
    id: '1775640447943',
    categoryId: 'cs2nfa',
    title: '💚ПРАЙМ АКК CS2 NFA (Отлега, 3ч Гарант) ∙ CS2 PRIME NFA ACC (Inactive, 3h warranty)',
    price: 59,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: '3 часа',
    inactivity: '60+ дней',
    hours: 950,
    rank: 'Калибровка',
    description: `Аккаунт CS2 с Праймом и отлегой от 2 месяцев.`
  },
  {
    id: '1775640229196',
    categoryId: 'cs2nfa',
    title: '🔥ПРАЙМ АКК CS2 NFA (СКИНЫ, 3ч ГАРАНТ) ∙ CS2 PRIME NFA ACC (SKINS, 3h warranty)',
    price: 67,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: '3 часа',
    inactivity: 'Есть отлега',
    hours: 1100,
    rank: 'Премьер открыт',
    description: `Аккаунт со скинами в инвентаре CS2.`
  },
  {
    id: '1779354634334',
    categoryId: 'cs2nfa',
    title: '💠ПРАЙМ АКК CS2 NFA (25K+ Рейтинг)',
    price: 109,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: '3 часа',
    inactivity: '30 дней',
    hours: 2400,
    rank: 'Премьер 25k+',
    description: `Высокий Premier рейтинг 25,000+ очков.`
  },
  {
    id: '1775685165996',
    categoryId: 'cs2nfa',
    title: '💰ПРАЙМ АКК CS2 NFA (Несколько ножей)',
    price: 189,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: '3 часа',
    inactivity: '45 дней',
    hours: 2900,
    rank: 'Премьер 18k',
    description: `Инвентарь с 2 или более ножами CS2.`
  },
  {
    id: '1776097317263',
    categoryId: 'cs2nfa',
    title: '💙ПРАЙМ АКК CS2 NFA (Большая отлега) ∙ CS2 PRIME NFA (long inactive)',
    price: 67,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: '3 часа',
    inactivity: '90+ дней',
    hours: 1300,
    rank: 'Калибровка',
    description: `Отлега от 3 месяцев.`
  },
  {
    id: '1776123877718',
    categoryId: 'cs2nfa',
    title: '🍍ПРАЙМ АКК CS2 NFA (Нож +Отлега) ∙ CS2 PRIME NFA ACC (Knife +Inactive)',
    price: 199,
    oldPrice: 209,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: '3 часа',
    inactivity: '70+ дней',
    hours: 2200,
    rank: 'Премьер открыт',
    description: `Нож в инвентаре + длительная отлега.`
  },
  {
    id: '1775990770112',
    categoryId: 'cs2nfa',
    title: '💜ПРАЙМ АКК CS2 NFA (10+ медалей) ∙ CS2 PRIME NFA ACC (10+ medals)',
    price: 67,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: '3 часа',
    inactivity: '40 дней',
    hours: 1900,
    rank: 'Премьер открыт',
    description: `10+ медалей за разные годы службы.`
  },
  {
    id: '1779212290251',
    categoryId: 'cs2nfa',
    title: '💜ПРАЙМ АКК CS2 NFA (15+ медалей) ∙ CS2 PRIME NFA ACC (10+ medals)',
    price: 89,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: '3 часа',
    inactivity: '50 дней',
    hours: 2800,
    rank: 'Премьер 17k',
    description: `15+ медалей в профиле CS2.`
  },
  {
    id: '1775991295371',
    categoryId: 'cs2nfa',
    title: '✴ ПРАЙМ АКК CS2 NFA (50+ lvl Steam) ∙ CS2 Prime NFA (50+ lvl Steam)',
    price: 79,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: '3 часа',
    inactivity: '30 дней',
    hours: 1500,
    rank: 'Премьер открыт',
    description: `Прокачанный уровень Steam 50+.`
  },
  {
    id: '1776263772424',
    categoryId: 'cs2nfa',
    title: '💠ПРАЙМ АКК CS2 NFA (20K+ Рейтинг)',
    price: 89,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: '3 часа',
    inactivity: '30 дней',
    hours: 1700,
    rank: 'Премьер 20k+',
    description: `Premier рейтинг от 20,000 очков.`
  },
  {
    id: '1787011694190',
    categoryId: 'cs2nfa',
    title: '🔥ПРАЙМ АКК CS2 NFA (СКИНЫ + ОТЛЕГА) ∙ CS2 PRIME NFA ACC (SKINS +INACTIVE)',
    price: 77,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: '3 часа',
    inactivity: '80 дней',
    hours: 1600,
    rank: 'Премьер открыт',
    description: `Скины + отлега.`
  },
  {
    id: '1776122172425',
    categoryId: 'cs2nfa',
    title: '💠ПРАЙМ АКК CS2 NFA (10K+ Рейтинг)',
    price: 69,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: '3 часа',
    inactivity: '30 дней',
    hours: 1100,
    rank: 'Премьер 10k+',
    description: `Premier рейтинг от 10,000 очков.`
  },
  {
    id: '1775985646591',
    categoryId: 'cs2nfa',
    title: '🍑ПРАЙМ CS2 NFA с Ножами (Жир) ∙ CS2 Prime NFA (High price knives)',
    price: 390,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: '3 часа',
    inactivity: '60 дней',
    hours: 3400,
    rank: 'Премьер 22k',
    description: `Дорогие ножи в инвентаре.`
  },
  {
    id: '1784207876422',
    categoryId: 'cs2nfa',
    title: '👑ПРАЙМ АКК CS2 NFA (Нож + Перчатки + Отлега) ∙ CS2 PRIME NFA ACC (Knife +Gloves+Inactive)',
    price: 259,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: 'На момент покупки',
    inactivity: 'Отлега',
    hours: 2600,
    rank: 'Премьер открыт',
    description: `Ножи + перчатки + отлега.`
  },
  {
    id: '1776522464373',
    categoryId: 'cs2nfa',
    title: '✴ ПРАЙМ АКК CS2 NFA (30+ lvl Steam) ∙ CS2 Prime NFA (30+ lvl Steam)',
    price: 69,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: '3 часа',
    inactivity: '30 дней',
    hours: 1200,
    rank: 'Премьер открыт',
    description: `30+ уровень Steam.`
  },
  {
    id: '1776181346459',
    categoryId: 'cs2nfa',
    title: '💠ПРАЙМ АКК CS2 NFA (15K+ Рейтинг)',
    price: 79,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: '3 часа',
    inactivity: '30 дней',
    hours: 1400,
    rank: 'Премьер 15k+',
    description: `Premier рейтинг от 15,000 очков.`
  },
  {
    id: '1775684701453',
    categoryId: 'cs2nfa',
    title: '💜ПРАЙМ АКК CS2 NFA (Редкие медали) ∙ CS2 PRIME NFA (Rare medals)',
    price: 67,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: '3 часа',
    inactivity: '45 дней',
    hours: 1800,
    rank: 'Премьер открыт',
    description: `Редкие памятные медали.`
  },
  {
    id: '1777653712237',
    categoryId: 'cs2nfa',
    title: '✴ ПРАЙМ АКК CS2 NFA (100+ lvl Steam) ∙ CS2 Prime NFA (100+ lvl Steam)',
    price: 99,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: '3 часа',
    inactivity: '30 дней',
    hours: 3100,
    rank: 'Премьер 19k',
    description: `Эксклюзивный уровень Steam 100+.`
  },

  // ── FULL ACCESS CS2 ──
  {
    id: '1773149236916',
    categoryId: 'cs2full',
    categoryName: 'CS2 PRIME FULL ACCESS',
    title: '💖 ПРАЙМ АККАУНТ CS2 ПОЛНЫЙ ДОСТУП ∙ PRIME CS2 FULL ACCESS',
    price: 450,
    oldPrice: null,
    delivery: 'Ручная выдача',
    emailChange: 'Да',
    warranty: 'Бессрочно',
    inactivity: '100% перепривязка',
    hours: 500,
    rank: 'Калибровка',
    description: `Личный аккаунт с Прайм статусом. Полная перепривязка на вашу почту.`
  },
  {
    id: '1773149507447',
    categoryId: 'cs2full',
    categoryName: 'CS2 PRIME FULL ACCESS',
    title: '✔️ПРАЙМ АКК CS2 (ОТЛЕГА и ПРЕМЬЕР) PRIME ACC CS2 (INACTIVE +PREMIER)',
    price: 670,
    oldPrice: 699,
    delivery: 'Ручная выдача',
    emailChange: 'Да',
    warranty: 'Бессрочно',
    inactivity: '180+ дней',
    hours: 1400,
    rank: 'Премьер 15k',
    description: `Полный доступ с солидной отлегой и активным рейтингом Премьер.`
  },
  {
    id: '1773149343244',
    categoryId: 'cs2full',
    categoryName: 'CS2 PRIME FULL ACCESS',
    title: '⚡️ПРАЙМ АКК С ОТЛЕГОЙ ∙ Полный доступ ∙ Prime acc CS2 (Full Access, with inactive)',
    price: 550,
    oldPrice: null,
    delivery: 'Ручная выдача',
    emailChange: 'Да',
    warranty: 'Бессрочно',
    inactivity: '90+ дней',
    hours: 800,
    rank: 'Калибровка',
    description: `Прайм аккаунт с полной сменой почты и отлегой.`
  },
  {
    id: '1773149459060',
    categoryId: 'cs2full',
    categoryName: 'CS2 PRIME FULL ACCESS',
    title: '✳️ПРАЙМ АКК CS2 (ОТКРЫТ ПРЕМЬЕР) PRIME ACC CS2 (PREMIER)',
    price: 480,
    oldPrice: 490,
    delivery: 'Ручная выдача',
    emailChange: 'Да',
    warranty: 'Бессрочно',
    inactivity: '45 дней',
    hours: 900,
    rank: 'Премьер открыт',
    description: `Полный доступ с открытым Premier режимом.`
  },
  {
    id: '1777990083739',
    categoryId: 'cs2full',
    categoryName: 'CS2 PRIME FULL ACCESS',
    title: '💚АККАУНТ С НОЖОМ ∙ ТРЕЙД-БАН ∙ Без VAС ∙ Можно регать FACEIT',
    price: 2900,
    oldPrice: 3900,
    delivery: 'Ручная выдача',
    emailChange: 'Да',
    warranty: 'Бессрочно',
    inactivity: 'Чистый Faceit',
    hours: 2800,
    rank: 'Faceit Ready',
    description: `Аккаунт с дорогим ножом и трейд-баном. Без VAC-блокировок, доступен Faceit.`
  },

  // ── БЕЗ ПРАЙМА ──
  {
    id: '1773149575646',
    categoryId: 'cs2noprime',
    categoryName: 'CS2 БЕЗ ПРАЙМА',
    title: '⭐️АККАУНТ C МЕДАЛЬЮ В CS2 ∙ CS2 ACC WITH COIN',
    price: 15,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: 'На момент покупки',
    inactivity: '30 дней',
    hours: 180,
    rank: 'Без прайма',
    description: `Аккаунт с памятной медалью/монетой в CS2.`
  },
  {
    id: '1774832016647',
    categoryId: 'cs2noprime',
    categoryName: 'CS2 БЕЗ ПРАЙМА',
    title: '✌АККАУНТ 2 ПРИВАТ РАНГ ∙ ACC 2 Private rank',
    price: 12,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: 'На момент покупки',
    inactivity: '15 дней',
    hours: 45,
    rank: '2 Ранг',
    description: `Готов для входа в Matchmaking.`
  },
  {
    id: '1773149644991',
    categoryId: 'cs2noprime',
    categoryName: 'CS2 БЕЗ ПРАЙМА',
    title: '⌛️ АККАУНТ 300+ ЧАСОВ CS2 ∙ CS2 ACC WITH HOURS',
    price: 7,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: 'На момент покупки',
    inactivity: '30 дней',
    hours: 320,
    rank: '300+ Часов',
    description: `Аккаунт с наигранными 300+ часами.`
  },

  // ── RUST ──
  {
    id: '1773149703177',
    categoryId: 'rust',
    categoryName: 'RUST ⚙️',
    title: '💯АККАУНТ RUST',
    price: 450,
    oldPrice: null,
    delivery: 'Ручная выдача',
    emailChange: 'Да',
    warranty: 'На момент покупки',
    inactivity: '100% перепривязка',
    hours: 600,
    rank: 'Лицензия Rust',
    description: `✅ АККАУНТЫ БЕЗ БЛОКИРОВОК/БАНОВ В РАСТЕ ✅ АККАУНТЫ СО СМЕНОЙ ДАННЫХ Вы получаете ЛОГИН/ПАРОЛЬ и ПОЧТА/ПАРОЛЬ (Вход через клиент Steam) ✅ На аккаунты действует ГАРАНТИЯ на момент покупки. По всем вопросам в ТГ: @HackerShopSupport`,
    reviews: [
      { author: 'fuckshadovs', rating: 5, text: 'купил акк с растом, все пиздато', date: '10.03.2026' }
    ]
  },
  {
    id: '1775207394067',
    categoryId: 'rust',
    categoryName: 'RUST ⚙️',
    title: '♦️АККАУНТ РАСТ NFA ∙ RUST NFA',
    price: 49,
    oldPrice: 59,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: '3 часа',
    inactivity: '60 дней',
    hours: 450,
    rank: 'NFA Rust',
    description: `NFA доступ к Rust с отлегой.`
  },

  // ── CS2 CFG ──
  {
    id: '1779552161498',
    categoryId: 'cs2cfg',
    categoryName: 'CS2 CFG & НАСТРОЙКИ',
    title: '🅿️PLAGUE CS2 CFG🅿️',
    price: 39,
    oldPrice: 79,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: 'Мгновенно',
    inactivity: 'Актуально 2026',
    hours: 0,
    rank: 'Legit / Rage',
    description: `Приватный легит конфиг для Plague CS2.`
  },
  {
    id: '1779552968150',
    categoryId: 'cs2cfg',
    categoryName: 'CS2 CFG & НАСТРОЙКИ',
    title: '🟡MIDNIGHT CS2 CFG🟡',
    price: 59,
    oldPrice: 109,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: 'Мгновенно',
    inactivity: 'Актуально 2026',
    hours: 0,
    rank: 'Pro Legit',
    description: `Топовый конфиг Midnight CS2: плавный аим, идеальный спрей.`
  },
  {
    id: '1777982299416',
    categoryId: 'cs2cfg',
    categoryName: 'CS2 CFG & НАСТРОЙКИ',
    title: '🟠MEMESENSE CS2 CFG🟠',
    price: 79,
    oldPrice: 199,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: 'Мгновенно',
    inactivity: 'Актуально 2026',
    hours: 0,
    rank: 'Legit / Visuals',
    description: `Настройки Memesense CS2 для незаметной игры.`
  },
  {
    id: '1777983717957',
    categoryId: 'cs2cfg',
    categoryName: 'CS2 CFG & НАСТРОЙКИ',
    title: '🔵NEVERLOSE CS2 CFG🔵',
    price: 249,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: 'Мгновенно',
    inactivity: 'Актуально 2026',
    hours: 0,
    rank: 'HVH Dominance',
    description: `Мощнейший конфиг Neverlose CS2.`
  },
  {
    id: '1777983787500',
    categoryId: 'cs2cfg',
    categoryName: 'CS2 CFG & НАСТРОЙКИ',
    title: '☆ ASTRAL CS2 CFG ☆',
    price: 249,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: 'Мгновенно',
    inactivity: 'Актуально 2026',
    hours: 0,
    rank: 'Astral Legit',
    description: `Приватные настройки Astral CS2.`
  },
  {
    id: '1777983450684',
    categoryId: 'cs2cfg',
    categoryName: 'CS2 CFG & НАСТРОЙКИ',
    title: '🟢Gamesense(Skeet) CS2 CFG🟢',
    price: 399,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: 'Мгновенно',
    inactivity: 'Актуально 2026',
    hours: 0,
    rank: 'Skeet Private',
    description: `Элитный приватный конфиг для Gamesense (Skeet).`
  },

  // ── STEAM ──
  {
    id: '1775666229055',
    categoryId: 'steam',
    categoryName: 'Steam Товары',
    title: '🎁12 НАГРАД STEAM',
    price: 19,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: 'Автовыдача',
    inactivity: '12 наград',
    hours: 0,
    rank: 'Очки профиля',
    description: `12 наград для вашего профиля Steam. Быстрое начисление очков.`
  },
  {
    id: '1775666358056',
    categoryId: 'steam',
    categoryName: 'Steam Товары',
    title: '🎁24 НАГРАДЫ STEAM',
    price: 59,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: 'Автовыдача',
    inactivity: '24 награды',
    hours: 0,
    rank: 'Очки профиля',
    description: `24 награды для прокачки профиля Steam.`
  },
  {
    id: '1775931316554',
    categoryId: 'steam',
    categoryName: 'Steam Товары',
    title: '✨ГИФТЫ ИГР STEAM НА ВАШ АККАУНТ ЗА 30%✨',
    price: 140,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: 'Гарантия выдачи',
    inactivity: 'Подарки Steam',
    hours: 0,
    rank: 'Steam Gift',
    description: `— КАК ЭТО РАБОТАЕТ: ВЫ ПИШЕТЕ НАМ, КАКУЮ ИГРУ ХОТИТЕ ПРИОБРЕСТИ. ОПЛАЧИВАЕТЕ 30% ОТ ЕЕ СТОИМОСТИ (ЕСЛИ ИГРА СТОИТ 1000руб то платите 300руб) И МЫ ОТПРАВЛЯЕМ ВАМ ГИФТ В ВИДЕ ИГРЫ, КОТОРУЮ ВЫ ВЫБРАЛИ! 🔥НАПИШИТЕ в ТГ @HackerShopSupport с пометкой #ГИФТ и указывайте какую игру желаете приобрести.`,
    reviews: [
      { author: 'Чебупицца', rating: 5, text: 'Купил раст подарком, поддержка отправила всё моментально, советую', date: '11.04.2026' }
    ]
  },
  {
    id: '1777559740328',
    categoryId: 'steam',
    categoryName: 'Steam Товары',
    title: '🔎ПОДБОР АККАУНТА STEAM',
    price: 99,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: 'Индивидуально',
    inactivity: 'Ручной подбор',
    hours: 0,
    rank: 'Подбор',
    description: `Персональный подбор аккаунта Steam с нужными играми, медалями или инвентарём.`
  },
  {
    id: '1783963938562',
    categoryId: 'steam',
    categoryName: 'Steam Товары',
    title: 'Виртуальные выделенные серверы',
    price: 99,
    oldPrice: null,
    delivery: 'Автовыдача',
    emailChange: 'Нет',
    warranty: 'Поддержка 24/7',
    inactivity: 'VDS / VPS',
    hours: 0,
    rank: 'VDS Cloud',
    description: `Надёжные виртуальные серверы для любых задач: размещения сайтов, веб-приложений, баз данных, игровых серверов, VPN, разработки, тестирования. Поддержка: @HackVPNSupport`,
    reviews: []
  }
];

const fileContent = `export const CATEGORIES = ${JSON.stringify(categories, null, 2)};\n\nexport const PRODUCTS = ${JSON.stringify(products, null, 2)};\n`;

fs.writeFileSync('c:\\Users\\iliyk\\Desktop\\hackershop-web\\src\\data\\mockData.js', fileContent);
console.log('Successfully written complete database with', products.length, 'real items!');
