import fs from 'fs';

const allProducts = [
  // 1-6. CS2 CFG
  {
    id: '1779552968150',
    categoryId: 'cs2cfg',
    cleanTitle: 'MIDNIGHT CS2 CFG',
    englishTitle: 'MIDNIGHT CS2 CFG',
    summaryPurpose: 'Легит и семи-рейдж конфиг для Midnight CS2. Настроенные визуалы, плавный аимбот и триггербот.',
    itemType: 'cfg',
    price: 59,
    oldPrice: 109,
    inactivityDays: 0,
    specs: { access: 'Конфиг', hours: '—', medals: '—', rank: 'Legit / Semi-Rage', vac: 'Безопасно', warranty: 'Пожизненная', delivery: 'Автоматическая', inactivity: '0 дн.', emailChange: '—' },
    composition: { rank: 10, hours: 10, medals: 10, inventory: 10, access: 60 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 0,
    medalsVal: 0,
    description: 'Приватный конфиг для чита Midnight CS2. Идеален для игры в Premier и Faceit с незаметным аимом.',
    reviews: []
  },
  {
    id: '1779552161498',
    categoryId: 'cs2cfg',
    cleanTitle: 'PLAGUE CS2 CFG',
    englishTitle: 'PLAGUE CS2 CFG',
    summaryPurpose: 'Топовый конфиг для Plague CS2. Отличная оптимизация, пресеты под пистолеты, винтовки и снайперки.',
    itemType: 'cfg',
    price: 39,
    oldPrice: 79,
    inactivityDays: 0,
    specs: { access: 'Конфиг', hours: '—', medals: '—', rank: 'Legit / Visuals', vac: 'Безопасно', warranty: 'Пожизненная', delivery: 'Автоматическая', inactivity: '0 дн.', emailChange: '—' },
    composition: { rank: 10, hours: 10, medals: 10, inventory: 10, access: 60 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 0,
    medalsVal: 0,
    description: 'Настроенный конфиг Plague CS2. Плавная доводка, чистые визуалы без просадки FPS.',
    reviews: []
  },
  {
    id: '1777983450684',
    categoryId: 'cs2cfg',
    cleanTitle: 'GAMESENSE (SKEET) CS2 CFG',
    englishTitle: 'GAMESENSE SKEET CS2 CFG',
    summaryPurpose: 'Премиальный HVH и Legit сет для легендарного Gamesense (Skeet) в CS2.',
    itemType: 'cfg',
    price: 399,
    oldPrice: null,
    inactivityDays: 0,
    specs: { access: 'Конфиг', hours: '—', medals: '—', rank: 'HVH / Legit Pro', vac: 'Безопасно', warranty: 'Пожизненная', delivery: 'Автоматическая', inactivity: '0 дн.', emailChange: '—' },
    composition: { rank: 10, hours: 10, medals: 10, inventory: 10, access: 60 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 0,
    medalsVal: 0,
    description: 'Эксклюзивный конфиг Gamesense (Skeet). Мощнейший револьвер, скаут и автоснупа для HVH.',
    reviews: []
  },
  {
    id: '1777983787500',
    categoryId: 'cs2cfg',
    cleanTitle: 'ASTRAL CS2 CFG',
    englishTitle: 'ASTRAL CS2 CFG',
    summaryPurpose: 'Универсальный конфиг Astral CS2 с акцентом на Premier и соревновательный режим.',
    itemType: 'cfg',
    price: 249,
    oldPrice: null,
    inactivityDays: 0,
    specs: { access: 'Конфиг', hours: '—', medals: '—', rank: 'Premier Legit', vac: 'Безопасно', warranty: 'Пожизненная', delivery: 'Автоматическая', inactivity: '0 дн.', emailChange: '—' },
    composition: { rank: 10, hours: 10, medals: 10, inventory: 10, access: 60 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 0,
    medalsVal: 0,
    description: 'Конфиг Astral CS2. Идеальный баланс между эффективностью и беспалевностью.',
    reviews: []
  },
  {
    id: '1777983717957',
    categoryId: 'cs2cfg',
    cleanTitle: 'NEVERLOSE CS2 CFG',
    englishTitle: 'NEVERLOSE CS2 CFG',
    summaryPurpose: 'Топовый HVH & Scout пресет для Neverlose CS2. Максимальный урон и прострелы.',
    itemType: 'cfg',
    price: 249,
    oldPrice: null,
    inactivityDays: 0,
    specs: { access: 'Конфиг', hours: '—', medals: '—', rank: 'HVH Beast', vac: 'Безопасно', warranty: 'Пожизненная', delivery: 'Автоматическая', inactivity: '0 дн.', emailChange: '—' },
    composition: { rank: 10, hours: 10, medals: 10, inventory: 10, access: 60 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 0,
    medalsVal: 0,
    description: 'Пресет Neverlose CS2 от топовых игроков HVH сцены. Быстрый автостоп, скаут в голову.',
    reviews: []
  },
  {
    id: '1777982299416',
    categoryId: 'cs2cfg',
    cleanTitle: 'MEMESENSE CS2 CFG',
    englishTitle: 'MEMESENSE CS2 CFG',
    summaryPurpose: 'Популярный легит конфиг для Memesense CS2. Красивые чамсы и мягкий аим.',
    itemType: 'cfg',
    price: 79,
    oldPrice: 199,
    inactivityDays: 0,
    specs: { access: 'Конфиг', hours: '—', medals: '—', rank: 'Legit / Chams', vac: 'Безопасно', warranty: 'Пожизненная', delivery: 'Автоматическая', inactivity: '0 дн.', emailChange: '—' },
    composition: { rank: 10, hours: 10, medals: 10, inventory: 10, access: 60 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 0,
    medalsVal: 0,
    description: 'Настройки Memesense CS2 для комфортной игры без риска бана.',
    reviews: []
  },

  // 7-30. CS2 PRIME NFA
  {
    id: '1773838287151',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АКК CS2 NFA (3Ч ГАРАНТИЯ)',
    englishTitle: 'CS2 PRIME NFA (3H WARRANTY)',
    summaryPurpose: 'Базовый Prime аккаунт с гарантией на проверку. Доступ к Premier и дропу кейсов.',
    itemType: 'prime',
    price: 32,
    oldPrice: null,
    inactivityDays: 14,
    specs: { access: 'Prime NFA', hours: '450 ч.', medals: '1-2 медали', rank: 'Калибровка', vac: 'Чисто', warranty: '3 часа', delivery: 'Автоматическая', inactivity: '14 дней', emailChange: 'Нет' },
    composition: { rank: 30, hours: 40, medals: 20, inventory: 10, access: 40 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 450,
    medalsVal: 1,
    description: 'Прайм аккаунт CS2 формата NFA с 3-часовой гарантией на валидность.',
    reviews: []
  },
  {
    id: '1773838416806',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АКК CS2 NFA (ПРЕМЬЕР, 3Ч ГАРАНТ)',
    englishTitle: 'CS2 PRIME NFA (PREMIER, 3H WARRANTY)',
    summaryPurpose: 'Аккаунт с открытым режимом Premier. Калибровка пройдена или готова к игре.',
    itemType: 'prime',
    price: 42,
    oldPrice: null,
    inactivityDays: 20,
    specs: { access: 'Prime NFA', hours: '680 ч.', medals: '2 медали', rank: 'Premier Ready', vac: 'Чисто', warranty: '3 часа', delivery: 'Автоматическая', inactivity: '20 дней', emailChange: 'Нет' },
    composition: { rank: 50, hours: 50, medals: 30, inventory: 10, access: 40 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 680,
    medalsVal: 2,
    description: 'Prime NFA аккаунт с открытым рейтингом Премьер и наигранными часами.',
    reviews: []
  },
  {
    id: '1775639992648',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АКК CS2 NFA (4+ МЕДАЛИ, 3Ч ГАРАНТ)',
    englishTitle: 'CS2 PRIME NFA (4+ MEDALS, 3H WARRANTY)',
    summaryPurpose: 'Аккаунт с 4 и более медалями за службу разных лет. Красивый профиль.',
    itemType: 'medal',
    price: 59,
    oldPrice: null,
    inactivityDays: 30,
    specs: { access: 'Prime NFA', hours: '1 200 ч.', medals: '4+ медали', rank: 'Premier', vac: 'Чисто', warranty: '3 часа', delivery: 'Автоматическая', inactivity: '30 дней', emailChange: 'Нет' },
    composition: { rank: 50, hours: 60, medals: 80, inventory: 20, access: 40 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 1200,
    medalsVal: 4,
    description: 'Prime NFA профиль с богатой коллекцией медалей службы (2018–2024).',
    reviews: []
  },
  {
    id: '1775641016745',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АКК CS2 NFA (НОЖ / ПЕРЧАТКИ)',
    englishTitle: 'CS2 PRIME NFA (KNIFE / GLOVES)',
    summaryPurpose: 'Аккаунт с гарантированным ножом или перчатками в инвентаре CS2.',
    itemType: 'knife',
    price: 129,
    oldPrice: 199,
    inactivityDays: 30,
    specs: { access: 'Prime NFA', hours: '1 500 ч.', medals: '2-4 медали', rank: 'Premier', vac: 'Чисто', warranty: '3 часа', delivery: 'Автоматическая', inactivity: '30 дней', emailChange: 'Нет' },
    composition: { rank: 60, hours: 70, medals: 50, inventory: 90, access: 40 },
    hasKnife: true,
    hasGloves: false,
    hoursVal: 1500,
    medalsVal: 3,
    description: 'В инвентаре находится нож или перчатки. Prime активен, чистый статус без блокировок.',
    reviews: []
  },
  {
    id: '1776522464373',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АКК CS2 NFA (30+ LVL STEAM)',
    englishTitle: 'CS2 PRIME NFA (30+ LVL STEAM)',
    summaryPurpose: 'Прокачанный Steam профиль 30+ уровня с CS2 Prime и медалями.',
    itemType: 'prime',
    price: 69,
    oldPrice: null,
    inactivityDays: 45,
    specs: { access: 'Prime NFA', hours: '950 ч.', medals: '3 медали', rank: '30+ lvl Steam', vac: 'Чисто', warranty: '3 часа', delivery: 'Автоматическая', inactivity: '45 дней', emailChange: 'Нет' },
    composition: { rank: 40, hours: 60, medals: 50, inventory: 40, access: 40 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 950,
    medalsVal: 3,
    description: 'Аккаунт с высоким 30+ уровнем Steam, красивыми витринами и Prime статусом CS2.',
    reviews: []
  },
  {
    id: '1775640447943',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АКК CS2 NFA (ОТЛЕГА, 3Ч ГАРАНТ)',
    englishTitle: 'CS2 PRIME NFA (INACTIVE, 3H WARRANTY)',
    summaryPurpose: 'Прайм с надежной отлежкой от 30 дней. Повышенная стабильность владения.',
    itemType: 'prime',
    price: 59,
    oldPrice: null,
    inactivityDays: 35,
    specs: { access: 'Prime NFA', hours: '800 ч.', medals: '2 медали', rank: 'Inactive 35d+', vac: 'Чисто', warranty: '3 часа', delivery: 'Автоматическая', inactivity: '35 дней', emailChange: 'Нет' },
    composition: { rank: 40, hours: 50, medals: 40, inventory: 20, access: 40 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 800,
    medalsVal: 2,
    description: 'Аккаунт с реальной отлежкой от 30 дней. Идеально для спокойной игры в матчмейкинг.',
    reviews: []
  },
  {
    id: '1775640229196',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АКК CS2 NFA (СКИНЫ, 3Ч ГАРАНТ)',
    englishTitle: 'CS2 PRIME NFA (SKINS, 3H WARRANTY)',
    summaryPurpose: 'Аккаунт с красивым игровым инвентарем скинов CS2 (AK-47, M4A1-S, AWP).',
    itemType: 'inventory',
    price: 67,
    oldPrice: null,
    inactivityDays: 25,
    specs: { access: 'Prime NFA', hours: '1 100 ч.', medals: '3 медали', rank: 'Skins Loaded', vac: 'Чисто', warranty: '3 часа', delivery: 'Автоматическая', inactivity: '25 дней', emailChange: 'Нет' },
    composition: { rank: 50, hours: 60, medals: 50, inventory: 80, access: 40 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 1100,
    medalsVal: 3,
    description: 'В инвентаре присутствуют скины оружия разных коллекций, Prime статус и медали.',
    reviews: []
  },
  {
    id: '1784198119449',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АКК CS2 NFA (БОЛЬШАЯ ОТЛЕГА + ПРЕМЬЕР)',
    englishTitle: 'CS2 PRIME NFA (LONG INACTIVE + PREMIER)',
    summaryPurpose: 'Комбинация солидной отлежки (60+ дней) и активного режима Premier.',
    itemType: 'prime',
    price: 77,
    oldPrice: null,
    inactivityDays: 60,
    specs: { access: 'Prime NFA', hours: '1 400 ч.', medals: '3-5 медалей', rank: 'Premier 15k+', vac: 'Чисто', warranty: '3 часа', delivery: 'Автоматическая', inactivity: '60 дней', emailChange: 'Нет' },
    composition: { rank: 70, hours: 70, medals: 60, inventory: 30, access: 40 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 1400,
    medalsVal: 4,
    description: 'Большая отлежка от 60 дней и наигранный Premier рейтинг. Надежный вариант.',
    reviews: []
  },
  {
    id: '1779354634334',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АКК CS2 NFA (25K+ РЕЙТИНГ)',
    englishTitle: 'CS2 PRIME NFA (25K+ PREMIER)',
    summaryPurpose: 'Топовый аккаунт с элитным рейтингом Premier 25,000+ очков (Топ 0.5% мира).',
    itemType: 'rank',
    price: 109,
    oldPrice: null,
    inactivityDays: 30,
    specs: { access: 'Prime NFA', hours: '2 400 ч.', medals: '5+ медалей', rank: '25k+ Global', vac: 'Чисто', warranty: '3 часа', delivery: 'Автоматическая', inactivity: '30 дней', emailChange: 'Нет' },
    composition: { rank: 95, hours: 80, medals: 70, inventory: 40, access: 40 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 2400,
    medalsVal: 5,
    description: 'Элитный рейтинг 25,000+ очков в Premier режиме CS2. Топовый глобальный лидерборд.',
    reviews: []
  },
  {
    id: '1775685165996',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АКК CS2 NFA (НЕСКОЛЬКО НОЖЕЙ)',
    englishTitle: 'CS2 PRIME NFA (MULTIPLE KNIVES)',
    summaryPurpose: 'Аккаунт с 2 и более ножами в инвентаре. Премиальный выбор для игры со скинами.',
    itemType: 'knife',
    price: 189,
    oldPrice: null,
    inactivityDays: 30,
    specs: { access: 'Prime NFA', hours: '2 100 ч.', medals: '4 медали', rank: 'Multi-Knives', vac: 'Чисто', warranty: '3 часа', delivery: 'Автоматическая', inactivity: '30 дней', emailChange: 'Нет' },
    composition: { rank: 60, hours: 80, medals: 60, inventory: 95, access: 40 },
    hasKnife: true,
    hasGloves: false,
    hoursVal: 2100,
    medalsVal: 4,
    description: 'В инвентаре находится несколько ножей (Karambit, Butterfly, M9 или другие).',
    reviews: []
  },
  {
    id: '1776123877718',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АКК CS2 NFA (НОЖ + ОТЛЕГА)',
    englishTitle: 'CS2 PRIME NFA (KNIFE + INACTIVE)',
    summaryPurpose: 'Аккаунт с ножом и подтвержденной отлежкой от 45 дней. Максимальная надежность.',
    itemType: 'knife',
    price: 199,
    oldPrice: 209,
    inactivityDays: 45,
    specs: { access: 'Prime NFA', hours: '1 800 ч.', medals: '3-5 медалей', rank: 'Knife + Inactive', vac: 'Чисто', warranty: '3 часа', delivery: 'Автоматическая', inactivity: '45 дней', emailChange: 'Нет' },
    composition: { rank: 60, hours: 75, medals: 60, inventory: 90, access: 40 },
    hasKnife: true,
    hasGloves: false,
    hoursVal: 1800,
    medalsVal: 4,
    description: 'Редкое сочетание ножа в инвентаре и долгой отлежки владельца.',
    reviews: []
  },
  {
    id: '1775990770112',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АКК CS2 NFA (10+ МЕДАЛЕЙ)',
    englishTitle: 'CS2 PRIME NFA (10+ MEDALS)',
    summaryPurpose: 'Ветеранский аккаунт с 10 и более медалями за службу, монетами операций и значками.',
    itemType: 'medal',
    price: 67,
    oldPrice: null,
    inactivityDays: 40,
    specs: { access: 'Prime NFA', hours: '2 800 ч.', medals: '10+ медалей', rank: 'Veteran', vac: 'Чисто', warranty: '3 часа', delivery: 'Автоматическая', inactivity: '40 дней', emailChange: 'Нет' },
    composition: { rank: 70, hours: 85, medals: 95, inventory: 30, access: 40 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 2800,
    medalsVal: 10,
    description: 'Более 10 медалей разных годов в инвентаре. Солидный ветеранский профиль.',
    reviews: []
  },
  {
    id: '1779212290251',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АКК CS2 NFA (15+ МЕДАЛЕЙ)',
    englishTitle: 'CS2 PRIME NFA (15+ MEDALS)',
    summaryPurpose: 'Редчайший аккаунт с 15+ медалями и монетами турниров Pick\'Em.',
    itemType: 'medal',
    price: 89,
    oldPrice: null,
    inactivityDays: 50,
    specs: { access: 'Prime NFA', hours: '3 500 ч.', medals: '15+ медалей', rank: 'Collector', vac: 'Чисто', warranty: '3 часа', delivery: 'Автоматическая', inactivity: '50 дней', emailChange: 'Нет' },
    composition: { rank: 80, hours: 90, medals: 98, inventory: 40, access: 40 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 3500,
    medalsVal: 15,
    description: 'Коллекционный профиль CS2 с огромным набором памятных медалей и значков.',
    reviews: []
  },
  {
    id: '1776263772424',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АКК CS2 NFA (20K+ РЕЙТИНГ)',
    englishTitle: 'CS2 PRIME NFA (20K+ PREMIER)',
    summaryPurpose: 'Высокий рейтинг Premier 20,000+ очков. Рубиновый бейдж и победы в матчах.',
    itemType: 'rank',
    price: 89,
    oldPrice: null,
    inactivityDays: 30,
    specs: { access: 'Prime NFA', hours: '1 900 ч.', medals: '4 медали', rank: '20k+ Premier', vac: 'Чисто', warranty: '3 часа', delivery: 'Автоматическая', inactivity: '30 дней', emailChange: 'Нет' },
    composition: { rank: 85, hours: 75, medals: 60, inventory: 30, access: 40 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 1900,
    medalsVal: 4,
    description: '20k+ Premier рейтинг с высоким винрейтом и хорошим фактором доверия.',
    reviews: []
  },
  {
    id: '1775641197078',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АКК CS2 NFA (НОЖ + ПЕРЧАТКИ)',
    englishTitle: 'CS2 PRIME NFA (KNIFE + GLOVES BUNDLE)',
    summaryPurpose: 'Комплект: и нож, и перчатки на одном Prime аккаунте CS2.',
    itemType: 'knife',
    price: 209,
    oldPrice: null,
    inactivityDays: 30,
    specs: { access: 'Prime NFA', hours: '2 200 ч.', medals: '4 медали', rank: 'Knife + Gloves', vac: 'Чисто', warranty: '3 часа', delivery: 'Автоматическая', inactivity: '30 дней', emailChange: 'Нет' },
    composition: { rank: 70, hours: 80, medals: 60, inventory: 98, access: 40 },
    hasKnife: true,
    hasGloves: true,
    hoursVal: 2200,
    medalsVal: 4,
    description: 'Полный готовый сет со скином ножа и перчаток. Идеально для красивой игры.',
    reviews: []
  },
  {
    id: '1776097317263',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АКК CS2 NFA (БОЛЬШАЯ ОТЛЕГА)',
    englishTitle: 'CS2 PRIME NFA (LONG INACTIVE 90D+)',
    summaryPurpose: 'Аккаунт с отлежкой от 90 дней и выше. Проверен на валидность.',
    itemType: 'prime',
    price: 67,
    oldPrice: null,
    inactivityDays: 90,
    specs: { access: 'Prime NFA', hours: '1 300 ч.', medals: '3 медали', rank: 'Inactive 90d+', vac: 'Чисто', warranty: '3 часа', delivery: 'Автоматическая', inactivity: '90 дней', emailChange: 'Нет' },
    composition: { rank: 50, hours: 65, medals: 50, inventory: 20, access: 40 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 1300,
    medalsVal: 3,
    description: 'Глубокая отлежка 90+ дней. Полная безопасность и стабильность.',
    reviews: []
  },
  {
    id: '1775991295371',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АКК CS2 NFA (50+ LVL STEAM)',
    englishTitle: 'CS2 PRIME NFA (50+ LVL STEAM)',
    summaryPurpose: 'Прокачанный Steam аккаунт 50+ уровня с CS2 Prime и выслугой лет.',
    itemType: 'prime',
    price: 79,
    oldPrice: null,
    inactivityDays: 45,
    specs: { access: 'Prime NFA', hours: '1 600 ч.', medals: '4 медали', rank: '50+ lvl Steam', vac: 'Чисто', warranty: '3 часа', delivery: 'Автоматическая', inactivity: '45 дней', emailChange: 'Нет' },
    composition: { rank: 60, hours: 70, medals: 60, inventory: 50, access: 40 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 1600,
    medalsVal: 4,
    description: 'Высокий 50+ уровень Steam, фоны профиля, значки и CS2 Prime.',
    reviews: []
  },
  {
    id: '1787011694190',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АКК CS2 NFA (СКИНЫ + ОТЛЕГА)',
    englishTitle: 'CS2 PRIME NFA (SKINS + INACTIVE)',
    summaryPurpose: 'Скины в инвентаре и долгая отлежка владельца на одном аккаунте.',
    itemType: 'inventory',
    price: 77,
    oldPrice: null,
    inactivityDays: 45,
    specs: { access: 'Prime NFA', hours: '1 450 ч.', medals: '3 медали', rank: 'Skins + Inactive', vac: 'Чисто', warranty: '3 часа', delivery: 'Автоматическая', inactivity: '45 дней', emailChange: 'Нет' },
    composition: { rank: 60, hours: 65, medals: 50, inventory: 85, access: 40 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 1450,
    medalsVal: 3,
    description: 'Инвентарь со скинами оружия и гарантированная отлежка от 45 дней.',
    reviews: []
  },
  {
    id: '1776122172425',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АКК CS2 NFA (10K+ РЕЙТИНГ)',
    englishTitle: 'CS2 PRIME NFA (10K+ PREMIER)',
    summaryPurpose: 'Рейтинг Premier 10,000+ очков. Готов к соревновательной игре.',
    itemType: 'rank',
    price: 69,
    oldPrice: null,
    inactivityDays: 25,
    specs: { access: 'Prime NFA', hours: '850 ч.', medals: '2 медали', rank: '10k+ Premier', vac: 'Чисто', warranty: '3 часа', delivery: 'Автоматическая', inactivity: '25 дней', emailChange: 'Нет' },
    composition: { rank: 60, hours: 50, medals: 40, inventory: 20, access: 40 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 850,
    medalsVal: 2,
    description: '10,000+ очков в рейтинге Premier CS2. Отличный вариант для калибровок.',
    reviews: []
  },
  {
    id: '1775985646591',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ CS2 NFA С НОЖАМИ (ЖИР)',
    englishTitle: 'CS2 PRIME NFA (HIGH TIER KNIVES)',
    summaryPurpose: 'Жирный аккаунт с дорогими редкими ножами (Doppler, Fade, Marble Fade).',
    itemType: 'knife',
    price: 390,
    oldPrice: null,
    inactivityDays: 45,
    specs: { access: 'Prime NFA', hours: '3 200 ч.', medals: '6+ медалей', rank: 'High-Tier Knives', vac: 'Чисто', warranty: '3 часа', delivery: 'Автоматическая', inactivity: '45 дней', emailChange: 'Нет' },
    composition: { rank: 80, hours: 90, medals: 80, inventory: 99, access: 40 },
    hasKnife: true,
    hasGloves: true,
    hoursVal: 3200,
    medalsVal: 6,
    description: 'Премиум аккаунт с несколькими дорогими ножами и богатым инвентарем.',
    reviews: []
  },
  {
    id: '1784207876422',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АКК CS2 NFA (НОЖ + ПЕРЧАТКИ + ОТЛЕГА)',
    englishTitle: 'CS2 PRIME NFA (KNIFE + GLOVES + INACTIVE)',
    summaryPurpose: 'Максимальный NFA пак: нож, перчатки и долгая отлежка на аккаунте.',
    itemType: 'knife',
    price: 259,
    oldPrice: null,
    inactivityDays: 60,
    specs: { access: 'Prime NFA', hours: '2 600 ч.', medals: '5 медалей', rank: 'Knife + Gloves + Inact', vac: 'Чисто', warranty: '3 часа', delivery: 'Автоматическая', inactivity: '60 дней', emailChange: 'Нет' },
    composition: { rank: 75, hours: 85, medals: 70, inventory: 98, access: 40 },
    hasKnife: true,
    hasGloves: true,
    hoursVal: 2600,
    medalsVal: 5,
    description: 'Нож, перчатки, медали и отлежка 60+ дней. Один из самых надежных в категории.',
    reviews: []
  },
  {
    id: '1776181346459',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АКК CS2 NFA (15K+ РЕЙТИНГ)',
    englishTitle: 'CS2 PRIME NFA (15K+ PREMIER)',
    summaryPurpose: 'Рейтинг Premier 15,000+ очков (Master Tier) с чистой историей матчей.',
    itemType: 'rank',
    price: 79,
    oldPrice: null,
    inactivityDays: 30,
    specs: { access: 'Prime NFA', hours: '1 300 ч.', medals: '3 медали', rank: '15k+ Premier', vac: 'Чисто', warranty: '3 часа', delivery: 'Автоматическая', inactivity: '30 дней', emailChange: 'Нет' },
    composition: { rank: 75, hours: 65, medals: 50, inventory: 30, access: 40 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 1300,
    medalsVal: 3,
    description: '15k+ очков в Premier CS2. Пройдена калибровка, высокий ранг.',
    reviews: []
  },
  {
    id: '1775684701453',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АКК CS2 NFA (РЕДКИЕ МЕДАЛИ)',
    englishTitle: 'CS2 PRIME NFA (RARE MEDALS)',
    summaryPurpose: 'Аккаунт с редкими старыми монетами операций (Bravo, Phoenix, Vanguard).',
    itemType: 'medal',
    price: 67,
    oldPrice: null,
    inactivityDays: 45,
    specs: { access: 'Prime NFA', hours: '1 700 ч.', medals: '5+ редких', rank: 'Rare Medals', vac: 'Чисто', warranty: '3 часа', delivery: 'Автоматическая', inactivity: '45 дней', emailChange: 'Нет' },
    composition: { rank: 65, hours: 75, medals: 92, inventory: 35, access: 40 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 1700,
    medalsVal: 5,
    description: 'Коллекция редких винтажных медалей и монет турниров CS:GO.',
    reviews: []
  },
  {
    id: '1777653712237',
    categoryId: 'cs2nfa',
    cleanTitle: 'ПРАЙМ АКК CS2 NFA (100+ LVL STEAM)',
    englishTitle: 'CS2 PRIME NFA (100+ LVL STEAM)',
    summaryPurpose: 'Элитный аккаунт 100+ уровня Steam с Prime CS2 и богатым профилем.',
    itemType: 'prime',
    price: 99,
    oldPrice: null,
    inactivityDays: 60,
    specs: { access: 'Prime NFA', hours: '2 900 ч.', medals: '6 медалей', rank: '100+ lvl Steam', vac: 'Чисто', warranty: '3 часа', delivery: 'Автоматическая', inactivity: '60 дней', emailChange: 'Нет' },
    composition: { rank: 80, hours: 85, medals: 75, inventory: 60, access: 40 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 2900,
    medalsVal: 6,
    description: 'Уровень Steam 100+, витрины, фоны, значки и CS2 Prime статус.',
    reviews: []
  },

  // 31-33. CS2 БЕЗ ПРАЙМА
  {
    id: '1773149575646',
    categoryId: 'cs2noprime',
    cleanTitle: 'АККАУНТ С МЕДАЛЬЮ В CS2',
    englishTitle: 'CS2 ACC WITH COIN',
    summaryPurpose: 'Профиль для игры и калибровки. Памятная медаль/монета, 180 часов, доступ без Prime.',
    itemType: 'medal',
    price: 15,
    oldPrice: null,
    inactivityDays: 30,
    specs: { access: 'Без прайма', hours: '180 ч.', medals: '1 медаль', rank: 'Без прайма', vac: 'Чисто', warranty: 'Первый вход', delivery: 'Автоматическая', inactivity: '30 дней', emailChange: 'Нет' },
    composition: { rank: 20, hours: 40, medals: 60, inventory: 10, access: 30 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 180,
    medalsVal: 1,
    description: 'Аккаунт CS2 с памятной монетой / медалью в инвентаре. Наиграно 180 часов.',
    reviews: []
  },
  {
    id: '1774832016647',
    categoryId: 'cs2noprime',
    cleanTitle: 'АККАУНТ 2 ПРИВАТ РАНГ',
    englishTitle: 'ACC 2 PRIVATE RANK',
    summaryPurpose: '2-й приватный ранг для мгновенного входа в матчмейкинг без фарма уровней.',
    itemType: 'rank',
    price: 12,
    oldPrice: null,
    inactivityDays: 15,
    specs: { access: 'Без прайма', hours: '45 ч.', medals: '0 медалей', rank: '2 ранг', vac: 'Чисто', warranty: 'Первый вход', delivery: 'Автоматическая', inactivity: '15 дней', emailChange: 'Нет' },
    composition: { rank: 40, hours: 20, medals: 0, inventory: 0, access: 30 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 45,
    medalsVal: 0,
    description: 'Получен 2-й ранг. Доступны соревновательный режим и калибровка.',
    reviews: []
  },
  {
    id: '1773149644991',
    categoryId: 'cs2noprime',
    cleanTitle: 'АККАУНТ 300+ ЧАСОВ CS2',
    englishTitle: 'CS2 ACC WITH HOURS',
    summaryPurpose: 'Аккаунт с наигранными 300+ часами в CS2 для доверия и игры.',
    itemType: 'hours',
    price: 7,
    oldPrice: null,
    inactivityDays: 30,
    specs: { access: 'Без прайма', hours: '320 ч.', medals: '0 медалей', rank: 'Без прайма', vac: 'Чисто', warranty: 'Первый вход', delivery: 'Автоматическая', inactivity: '30 дней', emailChange: 'Нет' },
    composition: { rank: 10, hours: 80, medals: 0, inventory: 0, access: 30 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 320,
    medalsVal: 0,
    description: 'Наиграно более 300 часов в CS2. Отличная статистика для соревнований.',
    reviews: []
  },

  // 34-38. CS2 FULL ACCESS
  {
    id: '1773149236916',
    categoryId: 'cs2full',
    cleanTitle: 'ПРАЙМ АККАУНТ CS2 ПОЛНЫЙ ДОСТУП',
    englishTitle: 'PRIME CS2 FULL ACCESS',
    summaryPurpose: 'Полная перепривязка: доступ к родной почте, смена пароля и Steam Guard под ваш мейн.',
    itemType: 'prime',
    price: 450,
    oldPrice: null,
    inactivityDays: 45,
    specs: { access: 'Полный доступ', hours: '500 ч.', medals: '1-2 медали', rank: 'Premier', vac: 'Чисто', warranty: '14 дней', delivery: 'Автоматическая', inactivity: '45 дней', emailChange: 'Да' },
    composition: { rank: 40, hours: 50, medals: 30, inventory: 20, access: 95 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 500,
    medalsVal: 1,
    description: 'Полный доступ с родной почтой. Можно привязать свой телефон и двухфакторку.',
    reviews: []
  },
  {
    id: '1773149507447',
    categoryId: 'cs2full',
    cleanTitle: 'ПРАЙМ АКК CS2 (ОТЛЕГА И ПРЕМЬЕР, FULL ACCESS)',
    englishTitle: 'PRIME CS2 FULL ACCESS (INACTIVE + PREMIER)',
    summaryPurpose: 'Полный доступ, отлежка 180+ дней и открытый режим Premier для игры в рейтинг.',
    itemType: 'rank',
    price: 670,
    oldPrice: 699,
    inactivityDays: 180,
    specs: { access: 'Полный доступ', hours: '1 400 ч.', medals: '3 медали', rank: 'Premier 18k+', vac: 'Чисто', warranty: '30 дней', delivery: 'Автоматическая', inactivity: '180 дней', emailChange: 'Да' },
    composition: { rank: 75, hours: 70, medals: 60, inventory: 30, access: 98 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 1400,
    medalsVal: 3,
    description: 'Отлежка 180 дней, открытый Premier и полная перепривязка на вашу почту.',
    reviews: []
  },
  {
    id: '1773149343244',
    categoryId: 'cs2full',
    cleanTitle: 'ПРАЙМ АКК С ОТЛЕГОЙ (ПОЛНЫЙ ДОСТУП)',
    englishTitle: 'PRIME CS2 FULL ACCESS WITH INACTIVE',
    summaryPurpose: 'Полный доступ с родной почтой и подтвержденной отлежкой от 90 дней.',
    itemType: 'prime',
    price: 550,
    oldPrice: null,
    inactivityDays: 90,
    specs: { access: 'Полный доступ', hours: '900 ч.', medals: '2 медали', rank: 'Premier', vac: 'Чисто', warranty: '30 дней', delivery: 'Автоматическая', inactivity: '90 дней', emailChange: 'Да' },
    composition: { rank: 50, hours: 60, medals: 40, inventory: 20, access: 95 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 900,
    medalsVal: 2,
    description: 'Надежный аккаунт под мейн с отлежкой 90+ дней и доступом к родной почте.',
    reviews: []
  },
  {
    id: '1773149459060',
    categoryId: 'cs2full',
    cleanTitle: 'ПРАЙМ АКК CS2 (ОТКРЫТ ПРЕМЬЕР, FULL ACCESS)',
    englishTitle: 'PRIME CS2 FULL ACCESS (PREMIER READY)',
    summaryPurpose: 'Полный доступ с открытым режимом Premier и пройденной калибровкой.',
    itemType: 'rank',
    price: 480,
    oldPrice: 490,
    inactivityDays: 30,
    specs: { access: 'Полный доступ', hours: '750 ч.', medals: '2 медали', rank: 'Premier Ready', vac: 'Чисто', warranty: '14 дней', delivery: 'Автоматическая', inactivity: '30 дней', emailChange: 'Да' },
    composition: { rank: 70, hours: 55, medals: 40, inventory: 20, access: 95 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 750,
    medalsVal: 2,
    description: 'Полный доступ с родной почтой. Режим Premier открыт и готов к игре.',
    reviews: []
  },
  {
    id: '1777990083739',
    categoryId: 'cs2full',
    cleanTitle: 'АККАУНТ С НОЖОМ (ТРЕЙД-БАН, МОЖНО РЕГАТЬ FACEIT)',
    englishTitle: 'CS2 KNIFE ACC (TRADE BAN, FACEIT READY)',
    summaryPurpose: 'Аккаунт с дорогим ножом и трейд-баном. Можно играть на Faceit и в Premier вечно.',
    itemType: 'knife',
    price: 2900,
    oldPrice: 3900,
    inactivityDays: 90,
    specs: { access: 'Полный доступ', hours: '2 800 ч.', medals: '4 медали', rank: 'Faceit Ready', vac: 'Чисто', warranty: 'Бессрочно', delivery: 'Автоматическая', inactivity: '90 дней', emailChange: 'Да' },
    composition: { rank: 80, hours: 85, medals: 70, inventory: 99, access: 95 },
    hasKnife: true,
    hasGloves: false,
    hoursVal: 2800,
    medalsVal: 4,
    description: 'В инвентаре находится нож за $1,000+. Из-за трейд-бана цена снижена в разы. Можно играть в Premier и Faceit.',
    reviews: []
  },

  // 39-40. RUST
  {
    id: '1773149703177',
    categoryId: 'rust',
    cleanTitle: 'АККАУНТ RUST (ПОЛНЫЙ ДОСТУП)',
    englishTitle: 'RUST ACCOUNT FULL ACCESS',
    summaryPurpose: 'Лицензия Rust с полным доступом к родной почте. Чистая история серверов.',
    itemType: 'game',
    price: 450,
    oldPrice: null,
    inactivityDays: 45,
    specs: { access: 'Полный доступ', hours: '600 ч.', medals: 'Rust DLC', rank: 'Clean Steam', vac: 'Чисто', warranty: '14 дней', delivery: 'Автоматическая', inactivity: '45 дней', emailChange: 'Да' },
    composition: { rank: 30, hours: 60, medals: 20, inventory: 30, access: 95 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 600,
    medalsVal: 0,
    description: 'Лицензионный Rust с полным доступом и перепривязкой на вашу личную почту.',
    reviews: []
  },
  {
    id: '1775207394067',
    categoryId: 'rust',
    cleanTitle: 'АККАУНТ РАСТ NFA',
    englishTitle: 'RUST NFA ACCOUNT',
    summaryPurpose: 'Rust NFA с отлежкой для игры на любых серверах и вылазок.',
    itemType: 'game',
    price: 49,
    oldPrice: 59,
    inactivityDays: 60,
    specs: { access: 'Rust NFA', hours: '450 ч.', medals: 'Rust Game', rank: 'Clean', vac: 'Чисто', warranty: '3 часа', delivery: 'Автоматическая', inactivity: '60 дней', emailChange: 'Нет' },
    composition: { rank: 20, hours: 50, medals: 10, inventory: 20, access: 40 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 450,
    medalsVal: 0,
    description: 'Лицензия Rust формата NFA с подтвержденной отлежкой.',
    reviews: []
  },

  // 41-45. STEAM ТОВАРЫ & УСЛУГИ
  {
    id: '1775666358056',
    categoryId: 'steam',
    cleanTitle: '24 НАГРАДЫ STEAM ПРОФИЛЯ',
    englishTitle: '24 STEAM PROFILE AWARDS',
    summaryPurpose: '24 награды на ваш профиль (+9,600 очков Steam). Быстрая прокачка профиля.',
    itemType: 'awards',
    price: 59,
    oldPrice: null,
    inactivityDays: 0,
    specs: { access: 'Услуга', hours: '—', medals: '24 награды', rank: '+9,600 pts', vac: 'Безопасно', warranty: '100% гарантия', delivery: 'Автоматическая', inactivity: '0 дн.', emailChange: '—' },
    composition: { rank: 20, hours: 0, medals: 80, inventory: 20, access: 60 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 0,
    medalsVal: 24,
    description: 'Начисление 24 наград на ваш Steam профиль. Дает 9,600 очков в магазине Steam.',
    reviews: []
  },
  {
    id: '1775666229055',
    categoryId: 'steam',
    cleanTitle: '12 НАГРАД STEAM ПРОФИЛЯ',
    englishTitle: '12 STEAM PROFILE AWARDS',
    summaryPurpose: '12 наград на ваш профиль (+4,800 очков Steam) для покупки фонов и смайлов.',
    itemType: 'awards',
    price: 19,
    oldPrice: null,
    inactivityDays: 0,
    specs: { access: 'Услуга', hours: '—', medals: '12 наград', rank: '+4,800 pts', vac: 'Безопасно', warranty: '100% гарантия', delivery: 'Автоматическая', inactivity: '0 дн.', emailChange: '—' },
    composition: { rank: 20, hours: 0, medals: 60, inventory: 10, access: 60 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 0,
    medalsVal: 12,
    description: 'Начисление 12 наград на ваш профиль Steam. Дает 4,800 очков.',
    reviews: []
  },
  {
    id: '1775931316554',
    categoryId: 'steam',
    cleanTitle: 'ГИФТЫ ИГР STEAM НА ВАШ АККАУНТ ЗА 30%',
    englishTitle: 'STEAM GAME GIFTS AT 30% PRICE',
    summaryPurpose: 'Покупка любых игр в Steam гифтом со скидкой до 70% от цены магазина.',
    itemType: 'gift',
    price: 140,
    oldPrice: null,
    inactivityDays: 0,
    specs: { access: 'Услуга', hours: '—', medals: 'Любая игра', rank: 'Скидка 70%', vac: 'Безопасно', warranty: 'Пожизненная', delivery: 'Ручная (10 мин)', inactivity: '0 дн.', emailChange: '—' },
    composition: { rank: 10, hours: 0, medals: 10, inventory: 80, access: 70 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 0,
    medalsVal: 0,
    description: 'Отправка лицензионных игр Steam гифтом на ваш личный аккаунт всего за 30% стоимости.',
    reviews: []
  },
  {
    id: '1777559740328',
    categoryId: 'steam',
    cleanTitle: 'ПОДБОР АККАУНТА STEAM ПО ПАРАМЕТРАМ',
    englishTitle: 'CUSTOM STEAM ACCOUNT FINDER',
    summaryPurpose: 'Индивидуальный поиск аккаунта по вашим критериям: конкретные скины, медали, часы, игры.',
    itemType: 'service',
    price: 99,
    oldPrice: null,
    inactivityDays: 0,
    specs: { access: 'Услуга', hours: 'Индивидуально', medals: 'Подбор', rank: 'Любой', vac: 'Чисто', warranty: '100% гарантия', delivery: 'Ручная (оператор)', inactivity: '0 дн.', emailChange: 'Да' },
    composition: { rank: 50, hours: 50, medals: 50, inventory: 50, access: 80 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 0,
    medalsVal: 0,
    description: 'Оператор подберет аккаунт с точным набором скинов, медалей или игр по вашему бюджету.',
    reviews: []
  },
  {
    id: '1783963938562',
    categoryId: 'steam',
    cleanTitle: 'ВИРТУАЛЬНЫЕ ВЫДЕЛЕННЫЕ СЕРВЕРЫ (VDS)',
    englishTitle: 'VIRTUAL DEDICATED SERVERS (VDS)',
    summaryPurpose: 'Быстрые виртуальные серверы NVMe 1Gbps для хостинга, ботов, игровых серверов и VPN.',
    itemType: 'vds',
    price: 99,
    oldPrice: null,
    inactivityDays: 0,
    specs: { access: 'Сервер VDS', hours: '24/7', medals: '—', rank: '1Gbps Port', vac: 'Безопасно', warranty: '30 дней', delivery: 'Автоматическая', inactivity: '0 дн.', emailChange: '—' },
    composition: { rank: 10, hours: 10, medals: 10, inventory: 10, access: 90 },
    hasKnife: false,
    hasGloves: false,
    hoursVal: 0,
    medalsVal: 0,
    description: 'Надёжные виртуальные серверы для любых задач. Поддержка: @sharpbuy_support',
    reviews: []
  }
];

const categories = [
  { id: 'cs2noprime', title: 'АККАУНТЫ CS2 БЕЗ ПРАЙМА', shortCategory: 'CS2 NON-PRIME', subtitle: 'Аккаунты с медалями, часами и рангами для игры и калибровки', count: allProducts.filter(p => p.categoryId === 'cs2noprime').length, minPrice: 7, icon: 'target' },
  { id: 'cs2nfa', title: 'АККАУНТЫ CS2 PRIME NFA', shortCategory: 'CS2 PRIME NFA', subtitle: 'Прайм-аккаунты с отлегой, ножами, перчатками и рейтингом Премьер', count: allProducts.filter(p => p.categoryId === 'cs2nfa').length, minPrice: 32, icon: 'knife' },
  { id: 'cs2full', title: 'АККАУНТЫ CS2 FULL ACCESS', shortCategory: 'CS2 FULL ACCESS', subtitle: 'Полный доступ с перепривязкой на вашу личную почту и Steam Guard', count: allProducts.filter(p => p.categoryId === 'cs2full').length, minPrice: 450, icon: 'shield' },
  { id: 'rust', title: 'АККАУНТЫ RUST', shortCategory: 'RUST GAME', subtitle: 'Лицензионные аккаунты Rust с полным доступом и NFA с отлегой', count: allProducts.filter(p => p.categoryId === 'rust').length, minPrice: 49, icon: 'gear' },
  { id: 'cs2cfg', title: 'КОНФИГИ & НАСТРОЙКИ CS2', shortCategory: 'CS2 CFG', subtitle: 'Приватные конфиги Midnight, Plague, Memesense, Neverlose, Skeet, Astral', count: allProducts.filter(p => p.categoryId === 'cs2cfg').length, minPrice: 39, icon: 'chip' },
  { id: 'steam', title: 'STEAM ТОВАРЫ & УСЛУГИ', shortCategory: 'STEAM ASSETS', subtitle: 'Награды Steam, гифты игр за 30%, подбор аккаунтов и VDS серверы', count: allProducts.filter(p => p.categoryId === 'steam').length, minPrice: 19, icon: 'gift' }
];

const content = `export const CATEGORIES = ${JSON.stringify(categories, null, 2)};\n\nexport const PRODUCTS = ${JSON.stringify(allProducts, null, 2)};\n`;

fs.writeFileSync('src/data/mockData.js', content, 'utf8');
console.log(`Synced mockData.js with exactly ${allProducts.length} products!`);
